<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Tóm tắt bài học nhóm môn A: Toán, Tiếng Việt, Tiếng Anh.
 * Chỉ ghi summary khi bài chưa có (NULL hoặc rỗng) — chạy lại không ghi đè.
 * KHÔNG đăng ký vào DatabaseSeeder (coordinator tổng hợp sau).
 */
class LessonSummaryGroupASeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // ===== TIẾNG ANH =====
            15 => "- \"father\" nghĩa là bố; \"mother\" nghĩa là mẹ.\n- \"brother\" nghĩa là anh trai hoặc em trai; \"sister\" nghĩa là chị gái hoặc em gái.\n- \"grandfather\" nghĩa là ông; \"grandmother\" nghĩa là bà.\n- Ghép đúng từ tiếng Anh với nghĩa tiếng Việt của từng thành viên trong gia đình.\n- Dùng từ vựng gia đình để giới thiệu người thân, ví dụ \"My mother is a teacher.\"",
            16 => "- \"teacher\" là giáo viên; \"student\" là học sinh; \"book\" là quyển sách; \"pen\" là bút mực.\n- \"pencil\" là bút chì; \"eraser\" là cục tẩy; \"notebook\" là vở.\n- \"classroom\" là lớp học; \"school\" là trường học.\n- Đồ dùng học tập (pencil, ruler) để trong cặp; bàn ghế, bảng ở trong lớp học.\n- Đặt câu đơn giản với từ vựng trường học, ví dụ \"I write with a pen.\"",
            17 => "- Ngôi he/she/it: động từ thêm s/es (she goes).\n- Ngôi I/you/we/they: động từ giữ nguyên mẫu (they play).\n- Câu phủ định với he/she/it dùng \"doesn't\" + động từ nguyên mẫu.\n- Câu phủ định với I/you/we/they dùng \"don't\" + động từ nguyên mẫu.\n- Ghép đúng chủ ngữ với dạng động từ \"go\" hoặc \"goes\" phù hợp.",
            18 => "- \"on\" chỉ vị trí trên bề mặt: on the table, on the wall.\n- \"in\" chỉ vị trí bên trong: in the classroom.\n- \"under\" chỉ vị trí phía dưới.\n- Bếp, phòng ngủ ở trong nhà (indoors); vườn, sân chơi ở ngoài trời (outdoors).\n- Ghép đúng giới từ với từng câu mô tả vị trí.",
            119 => "- \"father\" nghĩa là bố; \"mother\" nghĩa là mẹ.\n- \"sister\" nghĩa là chị gái hoặc em gái; \"brother\" nghĩa là anh trai hoặc em trai.\n- \"grandfather\" nghĩa là ông; \"grandmother\" nghĩa là bà.\n- Nhận nghĩa của từ trong câu, ví dụ \"My mother is a teacher.\".\n- Ôn tập và mở rộng vốn từ chủ đề gia đình.",
            120 => "- \"teacher\" nghĩa là giáo viên; \"student\" nghĩa là học sinh.\n- \"book\" là quyển sách; \"notebook\" là vở; \"pen\" là bút mực; \"pencil\" là bút chì.\n- \"classroom\" là lớp học; \"school\" là trường học.\n- Nhận diện nghĩa của từ trong ngữ cảnh câu đơn giản.\n- Ôn tập và mở rộng vốn từ chủ đề trường học.",
            123 => "- Chủ ngữ \"I\" luôn đi với \"am\".\n- Ngôi thứ ba số ít (he, she, it) đi với \"is\".\n- Chủ ngữ số nhiều (you, we, they) đi với \"are\".\n- Câu hỏi đảo \"to be\" lên trước chủ ngữ: \"Are you a teacher?\".\n- Chia đúng \"am/is/are\" theo chủ ngữ trong câu.",
            124 => "- Thì hiện tại đơn diễn tả thói quen và sự thật hiển nhiên.\n- Ngôi thứ ba số ít: động từ thêm s/es (she goes, he watches).\n- Các ngôi còn lại: động từ giữ nguyên mẫu (they play).\n- Động từ tận cùng bằng \"o\" thêm \"es\": go thành goes.\n- Chia đúng động từ theo chủ ngữ trong câu.",
            19 => "- \"headache\" là đau đầu (head + ache); \"fever\" là sốt; \"cough\" là ho.\n- \"healthy\" là khoẻ mạnh; \"sick\" là ốm.\n- \"doctor\" là bác sĩ; \"nurse\" là y tá.\n- Ghép từ tiếng Anh với nghĩa tiếng Việt đúng.\n- Dùng từ vựng sức khỏe để nói về tình trạng cơ thể.",
            20 => "- \"ticket\" là vé; \"hotel\" là khách sạn; \"suitcase\" là vali.\n- \"train\" là tàu hoả; \"plane\" là máy bay.\n- \"by plane, by train, by bus, by bike\" chỉ phương tiện di chuyển.\n- Phân biệt đồ mang theo khi du lịch với địa điểm đến thăm.\n- Đặt câu đơn giản về chuyến đi, ví dụ \"We stay at a hotel when we travel.\"",
            121 => "- \"get up\" nghĩa là thức dậy; \"have breakfast\" nghĩa là ăn sáng.\n- \"do homework\" nghĩa là làm bài tập về nhà; \"brush teeth\" nghĩa là đánh răng.\n- Các cụm động từ thường dùng để diễn tả sinh hoạt hằng ngày.\n- Nhận nghĩa của cụm từ trong câu.\n- Mở rộng vốn từ chủ đề hoạt động hằng ngày.",
            122 => "- \"sunny\" là trời nắng; \"rainy\" là trời mưa; \"windy\" là nhiều gió.\n- \"rainbow\" nghĩa là cầu vồng.\n- Câu \"It's windy today.\" nghĩa là \"Hôm nay trời nhiều gió.\".\n- Tính từ thời tiết thường đứng sau \"is\" trong câu.\n- Mở rộng vốn từ chủ đề thời tiết và thiên nhiên.",
            125 => "- Câu phủ định với he/she/it: \"does not/doesn't\" + động từ nguyên mẫu.\n- Câu phủ định với I/you/we/they: \"do not/don't\" + động từ nguyên mẫu.\n- Câu hỏi với he/she/it: \"Does\" đứng đầu câu.\n- Câu hỏi với I/you/we/they: \"Do\" đứng đầu câu.\n- Sau \"do/does/does not\", động từ luôn ở dạng nguyên mẫu.",
            126 => "- Thì hiện tại tiếp diễn diễn tả hành động đang xảy ra tại thời điểm nói.\n- Cấu trúc: am/is/are + động từ thêm -ing.\n- \"I\" đi với \"am\"; he/she/it đi với \"is\"; you/we/they đi với \"are\".\n- Dấu hiệu nhận biết: now, at the moment.\n- Chia đúng \"am/is/are\" và dạng V-ing theo chủ ngữ.",
            127 => "- \"headache\" nghĩa là đau đầu; \"fever\" nghĩa là sốt.\n- \"doctor\" nghĩa là bác sĩ; \"nurse\" nghĩa là y tá.\n- \"take medicine\" nghĩa là uống thuốc.\n- Nhận nghĩa của từ vựng sức khỏe trong câu.\n- Mở rộng vốn từ chủ đề sức khỏe.",
            128 => "- \"ticket\" nghĩa là vé (vé xe, vé máy bay...); \"passport\" nghĩa là hộ chiếu.\n- \"beach\" nghĩa là bãi biển; \"souvenir\" nghĩa là đồ lưu niệm.\n- Nhận nghĩa của từ vựng du lịch trong câu.\n- Mở rộng vốn từ chủ đề du lịch.",
            129 => "- \"environment\" nghĩa là môi trường; \"pollution\" nghĩa là sự ô nhiễm.\n- \"recycle\" nghĩa là tái chế; \"plant trees\" nghĩa là trồng cây.\n- Nhận nghĩa của từ vựng môi trường trong câu.\n- Mở rộng vốn từ và ý thức bảo vệ môi trường.",
            130 => "- \"volunteer\" nghĩa là tình nguyện viên; \"charity\" nghĩa là từ thiện.\n- \"donate\" nghĩa là quyên góp, tặng; \"community\" nghĩa là cộng đồng.\n- Nhận nghĩa của từ vựng cộng đồng trong câu.\n- Mở rộng vốn từ chủ đề hoạt động cộng đồng.",
            371 => "- Hiện tại đơn diễn tả thói quen và sự thật hiển nhiên.\n- Ngôi thứ ba số ít: động từ thêm s/es (she goes, water boils).\n- Hiện tại tiếp diễn diễn tả hành động đang xảy ra: am/is/are + V-ing.\n- Dấu hiệu tiếp diễn: now, at the moment, Look!\n- Phân biệt \"every day\" (hiện tại đơn) với \"now\" (tiếp diễn).",
            372 => "- Quá khứ đơn diễn tả hành động đã xảy ra và kết thúc trong quá khứ.\n- Dấu hiệu: yesterday, last night, last week.\n- Động từ bất quy tắc đổi dạng (go thành went); có quy tắc thêm -ed.\n- Tương lai đơn: will + động từ nguyên mẫu, dùng cho dự đoán và quyết định lúc nói.\n- Phân biệt thì theo dấu hiệu thời gian trong câu.",
            373 => "- Cấu trúc câu điều kiện loại 1: If + hiện tại đơn, will + động từ nguyên mẫu.\n- Diễn tả điều kiện có thể xảy ra ở hiện tại hoặc tương lai.\n- Khi mệnh đề If đứng trước, dùng dấu phẩy ngăn cách hai mệnh đề.\n- Mệnh đề If không dùng \"will\".\n- Chia đúng động từ ở cả hai mệnh đề theo cấu trúc.",
            374 => "- Ôn cấu trúc: If + hiện tại đơn, will + động từ nguyên mẫu.\n- Chủ ngữ he/she ở mệnh đề If: động từ thêm s/es (studies, is late).\n- Mệnh đề chính: will + động từ nguyên mẫu, không thêm s.\n- Nhận diện câu điều kiện loại 1 đúng cấu trúc.\n- Viết lại và sửa lỗi câu điều kiện loại 1.",
            375 => "- Bị động hiện tại đơn: am/is/are + V-ed/V3 (are made).\n- Bị động quá khứ đơn: was/were + V-ed/V3 (was written thành written).\n- Bị động tương lai đơn: will be + V-ed/V3 (will be built).\n- Bị động hiện tại tiếp diễn: am/is/are + being + V-ed/V3.\n- Chuyển câu chủ động sang bị động, chia \"be\" đúng thì và số.",
            376 => "- Bị động với động từ khuyết thiếu: modal + be + V-ed (must be cleaned, should be finished).\n- Bị động hiện tại hoàn thành: have/has + been + V-ed.\n- Câu có hai tân ngữ: có thể đưa tân ngữ gián tiếp hoặc trực tiếp lên làm chủ ngữ.\n- Nhớ dạng V3 của động từ bất quy tắc: built, written, given.\n- Chuyển đúng sang bị động theo thì và modal.",
            377 => "- Tường thuật phải lùi thì: hiện tại đơn thành quá khứ đơn, will thành would.\n- Đổi đại từ và trạng từ chỉ thời gian: I thành she/he, tomorrow thành the next day.\n- Câu hỏi Yes/No: asked + if/whether + S + V, không đảo ngữ.\n- Câu hỏi Wh-: asked + từ để hỏi + S + V, không đảo ngữ.\n- Giữ đúng thứ tự S + V sau từ nối trong câu tường thuật.",
            378 => "- Mệnh lệnh tường thuật: told/asked + tân ngữ + to-V.\n- Mệnh lệnh phủ định: told + tân ngữ + not to-V.\n- Yêu cầu lịch sự: asked + tân ngữ + to-V.\n- Câu điều kiện loại 2, 3 khi tường thuật giữ nguyên thì.\n- Đổi đại từ cho phù hợp: me thành her/him.",
            379 => "- Mệnh đề quan hệ chủ động rút gọn bằng V-ing: who plays thành playing.\n- Mệnh đề quan hệ bị động rút gọn bằng V-ed: which was made thành made.\n- Thì tiếp diễn chủ động cũng rút gọn bằng V-ing: who is talking thành talking.\n- Khi rút gọn, bỏ đại từ quan hệ và động từ \"be\".\n- Chọn dạng rút gọn đúng theo nghĩa chủ động hay bị động.",
            380 => "- Sau số thứ tự (the first, the second) rút gọn bằng to-V.\n- Sau so sánh nhất (the best, the tallest) rút gọn bằng to-V.\n- Dạng bị động của to-V: to be + V-ed (the house to be built).\n- Không nhầm to-V với V-ing/V-ed khi có dấu hiệu số thứ tự, so sánh nhất.\n- Luyện tập tổng hợp cả ba dạng rút gọn V-ing, V-ed và to-V.",
            381 => "- Trạng từ phủ định đứng đầu câu thì đảo trợ động từ lên trước chủ ngữ.\n- Never/Rarely + trợ động từ + S + V: Rarely does she go...\n- Hardly + quá khứ hoàn thành đảo ngữ: Hardly had he arrived when...\n- Đảo ngữ giữ nguyên thì; động từ sau trợ động từ ở dạng nguyên mẫu.\n- Nhận diện câu cần đảo ngữ theo trạng từ phủ định đầu câu.",
            382 => "- Đảo ngữ câu điều kiện loại 1: Should + S + V, bỏ \"if\".\n- Đảo ngữ câu điều kiện loại 2: Were + S..., bỏ \"if\".\n- Đảo ngữ câu điều kiện loại 3: Had + S + V-ed..., bỏ \"if\".\n- Only + cụm trạng từ đầu câu thì đảo trợ động từ: Only when... did he understand.\n- Viết lại câu điều kiện thành dạng đảo ngữ đúng.",

            // ===== TIẾNG VIỆT =====
            9 => "- Danh từ chỉ người, vật, hiện tượng: học sinh, sách.\n- Động từ chỉ hành động, trạng thái: bơi, hát.\n- Tính từ chỉ đặc điểm, tính chất: cao, đỏ.\n- Danh từ trả lời \"ai? cái gì?\"; động từ trả lời \"làm gì?\"; tính từ trả lời \"thế nào?\".\n- Xếp đúng từ vào nhóm danh từ, động từ, tính từ.",
            10 => "- Câu đơn gồm hai thành phần chính: chủ ngữ và vị ngữ.\n- Chủ ngữ trả lời \"ai? cái gì?\"; vị ngữ trả lời \"làm gì? thế nào? là gì?\".\n- Câu kể kết thúc bằng dấu chấm; câu hỏi kết thúc bằng dấu hỏi.\n- Câu cảm bộc lộ cảm xúc; câu khiến nêu yêu cầu, mệnh lệnh.\n- Xác định đúng chủ ngữ, vị ngữ và kiểu câu.",
            11 => "- Phân biệt cách viết các từ có dấu hỏi: nghỉ ngơi, mải mê.\n- Phân biệt cách viết các từ có dấu ngã: suy nghĩ, mãi mãi.\n- Ghi nhớ nghĩa của từ để viết đúng dấu thanh.\n- Nối từ với dấu thanh đúng của nó.\n- Viết đúng chính tả các từ dễ nhầm dấu hỏi, dấu ngã.",
            12 => "- Âm đầu \"ch\": chú, chim; âm đầu \"tr\": trâu, tre, mặt trời.\n- Âm đầu \"d\": dê, dao; âm đầu \"gi\": gió, giun; âm đầu \"r\": rừng.\n- Ghi nhớ cách viết đúng của từng từ theo âm đầu.\n- Phân loại từ theo nhóm âm đầu ch/tr và d/gi/r.\n- Điền âm đầu còn thiếu cho đúng chính tả.",
            107 => "- Từ đơn gồm một tiếng: sách.\n- Từ ghép gồm hai tiếng đều có nghĩa: bàn ghế, học sinh.\n- Từ láy lặp lại âm đầu hoặc vần: xinh xắn láy âm đầu x.\n- Đếm số tiếng để phân biệt từ đơn với từ nhiều tiếng.\n- Xếp đúng từ vào nhóm từ đơn, từ ghép, từ láy.",
            108 => "- Danh từ chỉ người, vật: bàn là danh từ.\n- Động từ chỉ hành động: nhảy, hót là động từ.\n- Tính từ chỉ đặc điểm, màu sắc: đỏ là tính từ.\n- Xác định động từ trong câu theo hành động của chủ ngữ.\n- Xếp đúng từ vào nhóm từ loại phù hợp.",
            111 => "- \"chăm chỉ\" (siêng năng) viết với ch; \"trong trẻo\" viết với tr.\n- \"sáng sủa\" viết với s.\n- \"rực rỡ\" viết với r.\n- Ghi nhớ nghĩa và cách viết đúng của từng từ.\n- Chọn từ viết đúng chính tả trong các đáp án.",
            112 => "- \"củ cải\" (loại rau) viết củ với dấu hỏi; \"nghỉ ngơi\" viết nghỉ với dấu hỏi.\n- \"vẻ đẹp\" viết vẻ với dấu hỏi.\n- \"suy nghĩ\" viết nghĩ với dấu ngã.\n- Ghi nhớ nghĩa của từ để viết đúng dấu thanh.\n- Chọn từ viết đúng chính tả trong các đáp án.",
            13 => "- Bài văn miêu tả gồm 3 phần: mở bài, thân bài, kết bài.\n- Mở bài giới thiệu đối tượng miêu tả.\n- Thân bài tả chi tiết từ bao quát đến cụ thể.\n- Kết bài nêu cảm nghĩ, tình cảm của người viết.\n- Dùng từ ngữ gợi hình (từ láy như \"lấp lánh\") để tả sinh động.",
            14 => "- So sánh dùng từ so sánh \"như\": trăng tròn như cái đĩa.\n- Nhân hoá gán đặc điểm con người cho sự vật.\n- Ẩn dụ gọi tên sự vật này bằng tên sự vật khác, không dùng từ so sánh.\n- Nhận diện đúng biện pháp tu từ theo dấu hiệu của câu.\n- Câu có từ \"như\" thường là so sánh, không phải ẩn dụ.",
            109 => "- Cụm danh từ có từ trung tâm là danh từ: phụ trước + trung tâm + phụ sau.\n- Ví dụ: những (phụ trước) + bông hoa (trung tâm) + đẹp (phụ sau).\n- Cụm động từ có từ trung tâm là động từ: đang chạy nhanh.\n- Cụm tính từ có từ trung tâm là tính từ: rất đẹp lắm.\n- Xác định từ trung tâm để gọi đúng tên cụm từ.",
            110 => "- Câu đơn chỉ có một cụm chủ ngữ - vị ngữ tạo thành một nòng cốt câu.\n- Chủ ngữ trả lời \"Ai?\"; vị ngữ trả lời \"Làm gì? Thế nào?\".\n- Ví dụ: \"Mẹ em / đang nấu cơm\" — chủ ngữ \"Mẹ em\", vị ngữ \"đang nấu cơm\".\n- Câu có hai cụm C-V trở lên là câu ghép, không phải câu đơn.\n- Phân tích đúng chủ ngữ, vị ngữ và nhận diện câu đơn.",
            113 => "- Tên riêng viết hoa chữ cái đầu mỗi tiếng: Hà Nội, Nguyễn Du.\n- Tên địa lí viết hoa chữ cái đầu mỗi tiếng: Sông Hồng.\n- Từ Hán Việt chỉ đất nước: Tổ quốc.\n- Phân biệt tên riêng với từ thường để viết hoa đúng.\n- Chọn cách viết đúng chính tả trong các đáp án.",
            114 => "- \"xán lạn\" (rực rỡ, tươi sáng) viết với x; \"trau chuốt\" viết trau với tr, chuốt với ch.\n- \"dè dặt\" (thận trọng) viết với dấu huyền.\n- Câu kể kết thúc bằng dấu chấm.\n- Ghi nhớ nghĩa của từ để viết đúng chính tả.\n- Đặt dấu câu đúng cuối mỗi kiểu câu.",
            115 => "- Văn miêu tả giúp người đọc hình dung sự vật như tận mắt trông thấy.\n- Từ gợi tả âm thanh: rì rào (tiếng gió, tiếng lá cây).\n- Từ gợi tả màu sắc: xanh biếc (màu xanh đẹp mắt).\n- Nhận diện câu văn miêu tả theo hình ảnh được gợi tả.\n- Dùng từ ngữ gợi hình, gợi cảm để tả sinh động.",
            116 => "- Bài văn tả người gồm 3 phần: mở bài, thân bài, kết bài.\n- Mở bài giới thiệu người được tả (là ai, quan hệ với mình).\n- Tả ngoại hình từ bao quát (dáng người, tuổi) đến chi tiết (khuôn mặt, mái tóc).\n- Kết bài nêu cảm nghĩ, tình cảm với người được tả.\n- Nhận diện câu tả ngoại hình trong đoạn văn.",
            117 => "- Tả cảnh cần quan sát tinh tế bằng nhiều giác quan.\n- Câu có từ \"như\" là so sánh: \"Sương giăng mờ như tấm voan mỏng\".\n- Gán hành động con người cho sự vật là nhân hoá: \"Hàng cây rì rào hát ca\".\n- Tả cảnh gắn với thời gian, không gian cụ thể: bình minh, hoàng hôn.\n- Dùng biện pháp tu từ để cảnh vật sinh động.",
            118 => "- Đoạn văn miêu tả hay cần hình ảnh sinh động và cảm xúc chân thành.\n- Tiếng ve râm ran là âm thanh đặc trưng gợi mùa hè.\n- Câu bộc lộ tình cảm là câu nêu cảm xúc của người viết.\n- Tránh lặp từ gây đơn điệu; thay bằng từ đồng nghĩa.\n- Cảm thụ đúng hình ảnh, cảm xúc trong đoạn văn miêu tả.",
            359 => "- Phong cách ngôn ngữ văn chương có 3 đặc trưng: hình tượng, truyền cảm, cá thể hoá.\n- Tính hình tượng: gợi hình ảnh cụ thể thay vì khái niệm trừu tượng.\n- Tính truyền cảm: truyền đạt cảm xúc, không chỉ thông tin.\n- Tính cá thể hoá: mỗi nhà văn có giọng riêng qua cách dùng từ, đặt câu.\n- Nhận diện văn bản văn chương qua hình ảnh, cảm xúc, giọng điệu riêng.",
            360 => "- Văn bản văn chương dùng nhiều biện pháp tu từ để tạo hình ảnh, cảm xúc.\n- Ngôn ngữ văn chương là ngôn ngữ toàn dân được chọn lọc, tinh luyện.\n- Phong cách báo chí: thời sự, ngắn gọn, khách quan — khác văn chương.\n- Nhận diện phong cách qua dấu hiệu: hình ảnh, cảm xúc, giọng điệu.\n- Phân biệt văn bản văn chương với văn bản báo chí.",
            361 => "- Chức năng chính của báo chí: thông tin nhanh về sự kiện thời sự.\n- Đặc trưng báo chí: thời sự (kịp thời), ngắn gọn, rõ ràng, dễ hiểu.\n- Báo chí hướng tới công chúng rộng rãi nên diễn đạt phải dễ hiểu.\n- Tính hình tượng đậm nét là của văn chương, không phải báo chí.\n- Nhận diện phong cách báo chí qua tính thời sự, ngắn gọn, khách quan.",
            362 => "- Bản tin: ngắn, khách quan, cung cấp thông tin cơ bản.\n- Bản tin đầy đủ trả lời: ai, việc gì, ở đâu, khi nào, diễn biến ra sao.\n- Phóng sự: sâu, có miêu tả, bình luận, sinh động hơn bản tin.\n- Tít báo: ngắn, trúng, hấp dẫn và phải trung thực.\n- Phân biệt bản tin với phóng sự theo độ dài và cách viết.",
            363 => "- Câu đơn gồm một cụm chủ ngữ - vị ngữ: \"Em / đang học bài\".\n- Câu ghép gồm nhiều vế, mỗi vế cấu tạo như một câu đơn.\n- Chủ ngữ nêu đối tượng được nói tới; vị ngữ trả lời Làm gì? Thế nào? Là gì?.\n- Xác định vế câu để phân biệt câu đơn với câu ghép.\n- Phân tích đúng chủ ngữ, vị ngữ trong câu.",
            364 => "- Trạng ngữ là thành phần phụ, bổ sung ý nghĩa hoàn cảnh cho câu.\n- Câu đặc biệt không phân tích được C-V: \"Ôi!\", \"Mưa!\".\n- Câu rút gọn có thể khôi phục C-V: \"Đang học bài.\" thành \"Em đang học bài.\".\n- Thành phần biệt lập tách khỏi nòng cốt câu: \"Này, bạn ơi!\".\n- Phân biệt câu đặc biệt với câu rút gọn.",
            365 => "- So sánh: có từ so sánh \"như\" — \"Mặt trời xuống biển như hòn lửa\".\n- Nhân hoá: gán đặc điểm con người cho sự vật, làm vật vô tri có hồn.\n- Ẩn dụ: gọi thẳng sự vật này bằng tên sự vật khác, không dùng từ so sánh.\n- Hoán dụ: lấy vật chứa chỉ vật bị chứa — \"Cả lớp vỗ tay\" chỉ học sinh.\n- Nhận diện đúng biện pháp tu từ theo dấu hiệu của câu.",
            366 => "- Điệp ngữ: lặp lại từ ngữ để nhấn mạnh, tạo nhịp điệu.\n- Liệt kê: kể ra hàng loạt tạo ấn tượng đầy đủ, dồn dập.\n- Nói quá (khoa trương): phóng đại sự vật — \"đứt từng khúc ruột\".\n- Chơi chữ: dùng từ đồng âm, đa nghĩa tạo hiệu quả hài hước, sâu sắc.\n- Nhận diện đúng biện pháp tu từ theo tác dụng của nó.",
            367 => "- Lỗi dùng từ sai nghĩa: dùng từ không đúng nghĩa trong ngữ cảnh.\n- Kết hợp từ phải tự nhiên, đúng nghĩa và đúng ngữ cảnh.\n- Đọc kĩ cả câu để phát hiện từ dùng chưa chính xác.\n- Sửa từ sai bằng từ đúng nghĩa, đúng kết hợp.\n- Kiểm tra lại câu sau khi sửa lỗi dùng từ.",
            368 => "- Câu thiếu chủ ngữ: trạng ngữ đứng đầu không thay thế được chủ ngữ.\n- Ví dụ: \"Qua bài thơ, cho em hiểu...\" sửa thành \"Bài thơ cho em hiểu...\".\n- Câu lủng củng: ý tứ rối rắm, các vế không liên kết chặt chẽ.\n- Xác định chủ ngữ, vị ngữ để phát hiện câu thiếu thành phần.\n- Viết lại câu cho đủ thành phần và mạch lạc.",
            369 => "- Phép lặp: lặp lại từ ngữ ở các câu để liên kết — \"Mẹ tôi... Mẹ tôi...\".\n- Phép thế: dùng từ thay thế — \"Lan rất chăm. Cô ấy luôn dậy sớm.\".\n- Phép nối: dùng từ nối liên kết ý nghĩa giữa các câu.\n- Phép tương phản: dùng cặp từ trái nghĩa (vui - buồn, nhanh - chậm).\n- Nhận diện đúng phép liên kết trong đoạn văn.",
            370 => "- Đoạn văn mạch lạc: liên kết chặt, đúng chủ đề, trình tự hợp lí.\n- Câu chủ đề nêu ý chính, thường đứng đầu hoặc cuối đoạn.\n- Trình tự triển khai hợp lí giúp người đọc theo dõi dễ dàng.\n- Dấu hiệu thiếu mạch lạc: câu không liên kết, ý lộn xộn, lạc đề.\n- Kiểm tra tính mạch lạc khi viết và sửa đoạn văn.",

            // ===== TOÁN =====
            1 => "- Đặt tính theo hàng, cộng từ hàng đơn vị; nhớ 1 sang hàng cao hơn khi tổng từ 10 trở lên.\n- Trừ có nhớ: mượn 1 ở hàng cao hơn khi chữ số bị trừ nhỏ hơn chữ số trừ.\n- Bài toán thực tế: xác định phép cộng hay phép trừ rồi tính tổng hoặc hiệu.\n- Kiểm tra lại kết quả bằng phép tính ngược.\n- Tính nhẩm nhanh bằng cách nhóm số thành tròn chục, tròn trăm.",
            2 => "- Nhân: đặt tính và nhân từng hàng, cộng dồn kết quả.\n- Chia: ước lượng thương từng hàng, nhân ngược và trừ dần.\n- Ghi nhớ bảng cửu chương để tính nhanh và đúng.\n- Số lẻ nhân số lẻ cho kết quả lẻ; số chẵn chia hết cho 2.\n- Phân biệt dấu nhân và dấu chia trong đề bài.",
            3 => "- Cùng mẫu số: cộng hoặc trừ tử số, giữ nguyên mẫu số.\n- Khác mẫu số: quy đồng mẫu số trước rồi mới cộng hoặc trừ.\n- Rút gọn kết quả về phân số tối giản, ví dụ 2/4 = 1/2.\n- Phân số có tử bằng mẫu thì bằng 1: 3/3 = 1.\n- Kiểm tra kết quả bằng cách quy đồng lại.",
            4 => "- Nhân phân số: nhân tử với tử, mẫu với mẫu rồi rút gọn.\n- Chia phân số: nhân với phân số nghịch đảo của số chia.\n- Phân số tử lớn hơn mẫu thì lớn hơn 1; tử nhỏ hơn mẫu thì nhỏ hơn 1.\n- Mọi số nhân với 0 đều bằng 0.\n- Rút gọn trước khi nhân để tính nhanh hơn.",
            91 => "- Đặt tính theo hàng: cộng hoặc trừ từ hàng đơn vị sang trái.\n- Cộng có nhớ: nhớ 1 sang hàng cao hơn khi tổng từ 10 trở lên.\n- Trừ có nhớ: mượn 1 ở hàng cao hơn khi không trừ được.\n- Tính nhanh: nhóm các số thành tròn chục, tròn trăm (23 + 77 = 100).\n- Số liền sau của n là n + 1: 9 999 + 1 = 10 000.",
            92 => "- Thứ tự thực hiện: trong ngoặc trước, nhân/chia trước, cộng/trừ sau.\n- Ghi nhớ các tích đặc biệt: 25 x 4 = 100 để tính nhanh.\n- Phép chia có dư: số bị chia = thương x số chia + số dư.\n- Tính giá trị biểu thức theo đúng thứ tự các phép tính.\n- Kiểm tra lại bằng cách tính ngược hoặc ước lượng.",
            95 => "- Cùng mẫu số: cộng hoặc trừ hai tử số, giữ nguyên mẫu số.\n- Rút gọn kết quả: chia cả tử và mẫu cho ước chung lớn nhất.\n- Hai phân số bằng nhau khi nhân hoặc chia cả tử và mẫu cho cùng một số.\n- Ví dụ: 1/2 = 2/4 khi nhân cả tử và mẫu với 2.\n- Viết kết quả dưới dạng phân số tối giản.",
            96 => "- Rút gọn: chia cả tử và mẫu cho ước chung, ví dụ 8/12 = 2/3.\n- Quy đồng: mẫu số chung nhỏ nhất là bội chung nhỏ nhất của các mẫu số.\n- So sánh phân số cùng mẫu dương: tử lớn hơn thì phân số lớn hơn.\n- So sánh phân số khác mẫu: quy đồng rồi so sánh tử số.\n- Phân số tối giản là phân số không rút gọn được nữa.",
            5 => "- Đơn thức gồm hệ số và phần biến, ví dụ 2x, 3x bình phương.\n- Nhân đơn thức: nhân hệ số với hệ số, cộng số mũ của cùng biến.\n- Bậc của đơn thức là tổng số mũ của các biến: 4x²y³ có bậc 5.\n- Hai đơn thức đồng dạng có cùng phần biến.\n- Thu gọn trước khi tính giá trị để tính nhanh hơn.",
            6 => "- Thứ tự thực hiện: trong ngoặc trước, nhân/chia trước, cộng/trừ sau.\n- Tính giá trị biểu thức: thay số vào chữ rồi tính theo thứ tự.\n- Ví dụ: x = 5 thì 2x + 3 = 2 x 5 + 3 = 13.\n- Biểu thức một biến chỉ chứa một chữ; hai biến chứa hai chữ.\n- Thay đúng giá trị vào đúng vị trí của biến.",
            7 => "- Góc nhọn nhỏ hơn 90 độ; góc vuông bằng 90 độ; góc tù lớn hơn 90 độ và nhỏ hơn 180 độ; góc bẹt bằng 180 độ.\n- Hai đường thẳng song song không có điểm chung, không bao giờ cắt nhau.\n- Góc bẹt tạo bởi hai tia đối nhau.\n- Nhận diện loại góc theo số đo của nó.\n- Vẽ và đọc đúng kí hiệu góc, đường thẳng.",
            8 => "- Tam giác có ba cạnh và ba góc; tổng ba góc bằng 180 độ.\n- Tam giác tù có một góc tù; tam giác vuông có một góc vuông.\n- Một tam giác có tối đa một góc vuông hoặc một góc tù.\n- Tìm góc còn lại: lấy 180 độ trừ hai góc đã biết.\n- Gọi tên tam giác ABC gồm các cạnh AB, BC, CA và các góc A, B, C.",
            93 => "- Luỹ thừa aⁿ là tích của n thừa số a: 2³ = 2 x 2 x 2 = 8.\n- Nhân hai luỹ thừa cùng cơ số: cộng số mũ (2³ x 2² = 2⁵).\n- Chia hai luỹ thừa cùng cơ số: trừ số mũ (a⁵ : a² = a³ với a khác 0).\n- 10ⁿ là số 1 tiếp theo là n chữ số 0: 10³ = 1 000.\n- Phân biệt aⁿ với a x n: 2³ = 8 khác 2 x 3 = 6.",
            94 => "- Tính luỹ thừa trước, rồi nhân/chia, cuối cùng cộng/trừ.\n- Dùng tính chất phân phối và nhóm số để tính nhanh.\n- Ví dụ: 12 x 25 = 3 x 4 x 25 = 3 x 100 = 300.\n- Luỹ thừa của một tích: (a x b)ⁿ = aⁿ x bⁿ.\n- Tính theo đúng thứ tự để tránh sai kết quả.",
            97 => "- Nhân phân số: nhân tử với tử, mẫu với mẫu rồi rút gọn.\n- Chia phân số: nhân với phân số nghịch đảo của số chia.\n- Hỗn số đổi ra phân số: tử = phần nguyên x mẫu + tử (1 1/2 = 3/2).\n- Mọi số nhân với 0 đều bằng 0.\n- Rút gọn kết quả về phân số tối giản.",
            98 => "- Quy đồng mẫu số chung trước khi cộng hoặc trừ nhiều phân số.\n- Dùng tính chất phân phối để tính nhanh: (2/3 + 1/4) x 12 = 8 + 3 = 11.\n- Bài toán phần - toàn thể: cả bể là 1, chia đều theo thời gian.\n- Tìm x: chuyển vế đổi dấu (x - 1/3 = 5/6 thì x = 5/6 + 1/3 = 7/6).\n- Kiểm tra kết quả bằng cách thay ngược vào đề.",
            99 => "- Biểu thức đại số chứa chữ đại diện cho số, ví dụ x + 5.\n- Diễn đạt bằng lời thành biểu thức: \"gấp đôi a rồi cộng 3\" là 2a + 3.\n- Tính giá trị: thay số vào chữ rồi thực hiện phép tính.\n- Ví dụ: x = 3 thì x + 7 = 10; x = 5 thì 2x = 10.\n- Viết đúng biểu thức theo diễn đạt của đề bài.",
            100 => "- Hai đơn thức đồng dạng có cùng phần biến: 3x² và 5x².\n- Cộng hoặc trừ đơn thức đồng dạng: cộng hoặc trừ hệ số, giữ nguyên phần biến.\n- Ví dụ: 3x + 5x = 8x; 7xy - 2xy = 5xy.\n- Thu gọn: nhóm các đơn thức đồng dạng rồi cộng hệ số.\n- Không cộng được các đơn thức không đồng dạng.",
            103 => "- Góc vuông bằng 90 độ; góc nhọn nhỏ hơn 90 độ; góc bẹt bằng 180 độ.\n- Hai đường thẳng vuông góc tạo thành góc 90 độ.\n- Góc bẹt có hai cạnh là hai tia đối nhau.\n- Nhận diện loại góc theo số đo cho trước.\n- Dùng thước đo góc đúng cách để đo và vẽ góc.",
            104 => "- Hai góc kề bù có tổng số đo bằng 180 độ.\n- Hai góc đối đỉnh thì bằng nhau.\n- Tìm góc kề bù: lấy 180 độ trừ góc đã biết.\n- Tia phân giác chia góc thành hai góc bằng nhau: 80 độ thành 40 độ + 40 độ.\n- Vẽ hình minh hoạ để xác định đúng cặp góc.",
            101 => "- Đa thức là tổng của các đơn thức (hạng tử).\n- Bậc của đa thức là bậc cao nhất của các hạng tử.\n- Thu gọn đa thức: cộng hoặc trừ các hạng tử đồng dạng.\n- Hệ số cao nhất là hệ số của hạng tử bậc cao nhất.\n- Đa thức một biến chỉ chứa một biến x.",
            102 => "- Nhân đơn thức với đơn thức: nhân hệ số, cộng số mũ của cùng biến.\n- Nhân đơn thức với đa thức: nhân với từng hạng tử, ví dụ x(x + 2) = x² + 2x.\n- Nhân hai đa thức: nhân mỗi hạng tử của ngoặc này với từng hạng tử của ngoặc kia.\n- Chú ý dấu khi nhân với số âm: 3x x (-2y) = -6xy.\n- Thu gọn kết quả sau khi khai triển.",
            105 => "- Tổng ba góc trong của một tam giác bằng 180 độ.\n- Tam giác cân có hai cạnh bên bằng nhau và hai góc ở đáy bằng nhau.\n- Tam giác đều có ba góc bằng nhau, mỗi góc 60 độ.\n- Tìm góc chưa biết: lấy 180 độ trừ hai góc đã biết.\n- Nhận diện tam giác cân, tam giác đều theo cạnh và góc.",
            106 => "- Hai tam giác đồng dạng có các góc tương ứng bằng nhau.\n- Các cạnh tương ứng tỉ lệ với nhau theo tỉ số đồng dạng k.\n- Tỉ số chu vi của hai tam giác đồng dạng bằng tỉ số đồng dạng k.\n- Trường hợp cạnh - cạnh - cạnh: ba cạnh tương ứng tỉ lệ thì hai tam giác đồng dạng.\n- Dùng tỉ số k để tính độ dài cạnh tương ứng.",
            263 => "- Mệnh đề là câu khẳng định có tính đúng hoặc sai xác định.\n- Câu hỏi, câu cảm thán không phải là mệnh đề.\n- Phủ định của \"với mọi\" là \"tồn tại\" và ngược lại, đồng thời phủ định nội dung.\n- Mệnh đề \"nếu... thì...\" đúng khi giả thiết đúng kéo theo kết luận đúng.\n- Kiểm tra tính đúng sai bằng kiến thức toán đã học.",
            264 => "- Phần tử thuộc tập hợp dùng kí hiệu thuộc; tập con dùng kí hiệu tập con.\n- Giao A giao B gồm các phần tử chung của A và B.\n- Hợp A hợp B gồm mọi phần tử thuộc A hoặc B, mỗi phần tử liệt kê một lần.\n- Liệt kê phần tử theo điều kiện cho trước để đếm số phần tử.\n- Vẽ sơ đồ Ven để minh hoạ giao, hợp của hai tập hợp.",
            265 => "- Đồ thị hàm số bậc hai là parabol; a > 0 bề lõm hướng lên, a < 0 hướng xuống.\n- Đỉnh parabol: hoành độ x = -b/2a, thay vào hàm số tìm tung độ.\n- Trục đối xứng là đường thẳng x = -b/2a.\n- a > 0: hàm số có giá trị nhỏ nhất tại đỉnh; a < 0: có giá trị lớn nhất tại đỉnh.\n- Vẽ parabol qua đỉnh, trục đối xứng và một vài điểm.",
            266 => "- Giải f(x) = 0 để tìm nghiệm (nếu có) bằng công thức nghiệm hoặc nhẩm nghiệm.\n- Delta < 0: tam thức luôn cùng dấu với hệ số a với mọi x.\n- a > 0: f(x) < 0 giữa hai nghiệm, f(x) > 0 ngoài hai nghiệm.\n- a < 0: dấu ngược lại với trường hợp a > 0.\n- Dựa vào bảng xét dấu để giải bất phương trình bậc hai.",
            267 => "- Góc đặc biệt cần nhớ: sin 30 độ = 1/2, cos 60 độ = 1/2, tan 45 độ = 1.\n- Hai góc phụ nhau: sin góc này bằng cos góc kia.\n- Công thức cơ bản: sin²a + cos²a = 1 với mọi góc a.\n- tan a = sin a / cos a với cos a khác 0.\n- Dùng đường tròn lượng giác để nhớ giá trị các góc đặc biệt.",
            268 => "- sin x = 0 khi x = k.pi; cos x = 1 khi x = k.2pi với k nguyên.\n- tan x = 1 khi x = pi/4 + k.pi vì tan có chu kì pi.\n- Giá trị tuyệt đối của sin x và cos x không vượt quá 1, nên sin x = 2 vô nghiệm.\n- Viết họ nghiệm đầy đủ với k là số nguyên.\n- Kiểm tra nghiệm có thoả điều kiện xác định (với tan, cot).",
            269 => "- Cấp số cộng: hiệu hai số hạng liên tiếp không đổi, gọi là công sai d.\n- Số hạng tổng quát: uₙ = u₁ + (n - 1)d.\n- Nhận diện cấp số cộng bằng cách kiểm tra hiệu các cặp số hạng liên tiếp.\n- Tổng n số hạng đầu: Sₙ = n(u₁ + uₙ)/2.\n- Ví dụ: 1 + 2 + ... + 10 = 10 x 11 / 2 = 55.",
            270 => "- Cấp số nhân: tỉ số hai số hạng liên tiếp không đổi, gọi là công bội q.\n- Số hạng tổng quát: uₙ = u₁.qⁿ⁻¹.\n- Nhận diện cấp số nhân bằng cách kiểm tra tỉ số các cặp số hạng liên tiếp.\n- Tổng n số hạng đầu: Sₙ = u₁(qⁿ - 1)/(q - 1) với q khác 1.\n- Tính từng số hạng rồi cộng để kiểm tra công thức tổng.",
            271 => "- Đạo hàm của hàm hằng bằng 0.\n- Đạo hàm của xⁿ bằng n.xⁿ⁻¹, ví dụ đạo hàm của x³ là 3x².\n- Đạo hàm của căn x là 1/(2 căn x) với x > 0; đạo hàm của 1/x là -1/x² với x khác 0.\n- Đạo hàm cho biết tốc độ thay đổi tức thời của hàm số.\n- Ghi nhớ bảng đạo hàm các hàm cơ bản.",
            272 => "- Đạo hàm của tổng: đạo hàm của (u + v) bằng u' + v'.\n- Đạo hàm của tích: đạo hàm của (u.v) bằng u'v + uv'.\n- Đạo hàm của thương: đạo hàm của (u/v) bằng (u'v - uv')/v².\n- Đạo hàm hàm hợp: đạo hàm của f(g(x)) bằng f'(g) nhân g'(x).\n- Áp dụng đúng quy tắc theo dạng của hàm số.",
            273 => "- y' > 0 trên khoảng nào thì hàm số đồng biến trên khoảng đó.\n- y' < 0 trên khoảng nào thì hàm số nghịch biến trên khoảng đó.\n- Điểm cực trị là nghiệm của y' = 0 mà y' đổi dấu khi đi qua đó.\n- y'' < 0 tại điểm dừng thì đạt cực đại; y'' > 0 thì đạt cực tiểu.\n- Lập bảng biến thiên để kết luận tính đơn điệu và cực trị.",
            274 => "- Trên đoạn [a; b]: giải y' = 0 tìm điểm dừng, so sánh giá trị tại các điểm dừng và hai đầu mút.\n- Parabol mở lên: đạt giá trị nhỏ nhất tại đỉnh; mở xuống: đạt giá trị lớn nhất tại đỉnh.\n- -1 ≤ sin x ≤ 1 nên giá trị lớn nhất của sin x là 1, giá trị nhỏ nhất là -1.\n- Dùng bất đẳng thức Cô-si: x + 1/x ≥ 2 với x > 0, dấu bằng khi x = 1.\n- Kết luận giá trị lớn nhất, nhỏ nhất kèm điểm đạt được.",
        ];

        $ids = array_keys($data);
        foreach (array_chunk($ids, 25) as $chunk) {
            $rows = DB::table('lessons')
                ->whereIn('id', $chunk)
                ->where(function ($q) {
                    $q->whereNull('summary')->orWhere('summary', '');
                })
                ->get(['id']);

            $targets = [];
            foreach ($rows as $row) {
                $targets[$row->id] = true;
            }

            foreach ($chunk as $id) {
                if (isset($targets[$id])) {
                    DB::table('lessons')->where('id', $id)->update(['summary' => $data[$id]]);
                }
            }
        }
    }
}
