<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Tóm tắt bài học NHÓM D: Âm nhạc, Mỹ thuật, Giáo dục thể chất, Trải nghiệm & Hướng nghiệp.
 *
 * Mỗi bài: 5-8 ý tóm tắt, mỗi ý một dòng bắt đầu bằng "- ", bám sát nội dung
 * câu hỏi hiện có của bài và kiến thức trọng tâm chương trình theo đúng khối lớp.
 * Không trích tác phẩm có bản quyền — chỉ tóm tắt kiến thức lý thuyết.
 *
 * Idempotent: chỉ cập nhật khi cột summary đang NULL hoặc rỗng; chạy lại không ghi đè.
 */
class LessonSummaryGroupDSeeder extends Seeder
{
    public function run(): void
    {
        $summaries = [
            33 => [
                '- Màu nóng gồm đỏ, cam, vàng — gợi cảm giác ấm áp, rực rỡ, sôi động.',
                '- Màu lạnh gồm xanh dương, xanh lá cây, tím — gợi cảm giác mát mẻ, yên bình, trầm lắng.',
                '- Đỏ là màu nóng mạnh nhất, dễ thu hút ánh nhìn; xanh dương là màu lạnh điển hình như bầu trời, mặt biển.',
                '- Muốn tranh vui tươi, năng động thì dùng gam nóng; muốn tranh nhẹ nhàng, sâu lắng thì dùng gam lạnh.',
                '- Kết hợp màu nóng – lạnh hợp lý giúp tranh cân bằng và sinh động hơn.',
            ],
            34 => [
                '- Ba màu cơ bản là đỏ, vàng, xanh dương — không pha được từ màu nào khác.',
                '- Đỏ + vàng = cam; vàng + xanh dương = xanh lá cây; đỏ + xanh dương = tím.',
                '- Cam, tím, xanh lá cây là ba màu thứ cấp, pha từ hai màu cơ bản.',
                '- Thêm màu trắng làm màu nhạt dần (đỏ + trắng = hồng); thêm màu đen làm màu đậm dần.',
                '- Khi pha màu nên cho từng ít một, khuấy đều để màu lên chuẩn.',
            ],
            35 => [
                '- Đường thẳng đứng gợi sự vững chắc, hiên ngang như thân cây, cột nhà.',
                '- Đường cong gợi sự mềm mại, uyển chuyển như dòng sông, làn tóc.',
                '- Đường zíc zắc (gấp khúc) gợi sự sôi động, mạnh mẽ như tia chớp.',
                '- Hình phẳng là hình hai chiều (tròn, vuông, tam giác); hình khối là hình ba chiều (cầu, hộp, trụ).',
                '- Chọn đường nét phù hợp giúp tranh diễn tả đúng cảm xúc muốn gửi gắm.',
            ],
            36 => [
                '- Bố cục là cách sắp xếp các hình, mảng trong tranh cho cân đối và sinh động.',
                '- Nhân vật chính đặt ở vị trí nổi bật để thu hút ánh nhìn đầu tiên của người xem.',
                '- Nhân vật phụ làm nền, phông nền tạo không gian cho bức tranh.',
                '- Vật ở gần vẽ to, rõ nét; vật ở xa vẽ nhỏ, mờ dần — tạo chiều sâu cho tranh.',
                '- Nhấn mạnh nhân vật chính và màu chủ đạo, tiết chế chi tiết rườm rà làm rối tranh.',
            ],
            37 => [
                '- Tranh Đông Hồ ra đời tại làng Đông Hồ, huyện Thuận Thành, tỉnh Bắc Ninh.',
                '- Giấy điệp làm từ vỏ sò điệp nghiền mịn quét lên giấy dó nên óng ánh, bền màu.',
                '- Màu vẽ từ nguyên liệu tự nhiên (cây cỏ, khoáng chất) nên trầm ấm, mộc mạc.',
                '- Tranh tiêu biểu: Gà trống tượng trưng sung túc, Đám cưới chuột châm biếm thói hối lộ, Hứng dừa thể hiện ước mơ đỗ đạt.',
                '- Tranh dân gian dùng nét mộc mạc, rõ ràng với đề tài gần gũi đời sống làng quê.',
            ],
            38 => [
                '- Tranh dân gian lấy đề tài từ đời sống làng quê gần gũi: chợ quê, trâu bò, lễ hội.',
                '- Quy trình vẽ tranh dân gian: chọn đề tài quen thuộc, phác bố cục rồi tô màu tươi rực rỡ.',
                '- Đường nét trong tranh dân gian mộc mạc, rõ ràng, dễ hiểu với mọi người.',
                '- Đề tài viễn tưởng, hiện đại chưa phù hợp với phong cách tranh dân gian.',
                '- Màu sắc tranh dân gian thường tươi, rực rỡ, tạo cảm giác vui tươi.',
            ],
            51 => [
                '- Khởi động 5–10 phút trước mỗi buổi tập: xoay khớp, chạy nhẹ tại chỗ, ép dẻo.',
                '- Khởi động làm nóng cơ, tăng linh hoạt khớp, giúp tránh chấn thương khi vận động mạnh.',
                '- Mỗi động tác xoay tác động trực tiếp lên khớp cùng tên: cổ, vai, hông, gối, cổ tay.',
                '- Khởi động chỉ gồm động tác nhẹ nhàng; bài tập nặng để dành cho phần tập chính.',
                '- Bỏ qua khởi động dễ bị chuột rút, bong gân khi vận động đột ngột.',
            ],
            53 => [
                '- Đi giày thể thao vừa chân, đế mềm để bảo vệ bàn chân và khớp gối khi vận động.',
                '- Mặc trang phục thoải mái, thấm mồ hôi, gọn gàng khi tập luyện.',
                '- Chuột rút: dừng lại và kéo giãn nhẹ; trầy xước: rửa sạch vết thương; chóng mặt: nghỉ ngay và báo thầy cô.',
                '- Không tập luyện khi quá no, không xô đẩy nhau khi chơi thể thao.',
                '- Uống nước từng ngụm nhỏ trước, trong và sau khi tập để bù nước cho cơ thể.',
            ],
            54 => [
                '- Mỗi đội bóng đá có 11 cầu thủ trên sân, trong đó có 1 thủ môn.',
                '- Trận đấu chính thức gồm 2 hiệp, mỗi hiệp 45 phút, nghỉ giữa hiệp 15 phút.',
                '- Việt vị: cầu thủ tấn công đứng gần khung thành đối phương hơn bóng và hậu vệ cuối khi đồng đội chuyền bóng.',
                '- Chỉ thủ môn được dùng tay trong vòng cấm; cầu thủ khác dùng tay chơi bóng là phạm luật.',
                '- Phạm lỗi nghiêm trọng bị thẻ vàng cảnh cáo, rất nghiêm trọng bị thẻ đỏ truất quyền thi đấu.',
            ],
            55 => [
                '- Mỗi đội bóng rổ có 5 cầu thủ thi đấu trên sân.',
                '- Cách tính điểm: ném trong vạch 2 điểm, ngoài vạch 3 điểm 3 điểm, ném phạt 1 điểm.',
                '- Dẫn bóng bằng một tay khi di chuyển; ôm bóng chạy nhiều bước là lỗi chạy bước.',
                '- Đẩy người, kéo áo đối phương là phạm luật trong bóng rổ.',
                '- Tranh bóng phải fair-play, không dùng tay chân thô bạo với đối thủ.',
            ],
            56 => [
                '- Học sinh nên vận động thể chất ít nhất 60 phút mỗi ngày với hoạt động vừa sức.',
                '- Ngủ đủ 8–9 tiếng mỗi đêm giúp cơ thể phát triển và tỉnh táo học tập.',
                '- Ăn đủ chất, nhiều rau xanh, hạn chế đồ ngọt và nước có gas.',
                '- Thức khuya và lười vận động làm suy giảm sức khỏe và kết quả học tập.',
                '- Duy trì thói quen tốt mỗi ngày quan trọng hơn tập nặng nhưng thất thường.',
            ],
            57 => [
                '- Sau khi tập ra nhiều mồ hôi: tắm rửa sạch sẽ, thay quần áo khô để tránh cảm lạnh.',
                '- Khăn mặt thấm mồ hôi dễ sinh vi khuẩn — phải giặt sạch và phơi khô sau mỗi lần dùng.',
                '- Không dùng chung khăn mặt, bình nước với người khác để tránh lây bệnh.',
                '- Cắt móng tay gọn gàng trước khi chơi thể thao tập thể để tránh làm xước bạn chơi.',
                '- Rửa tay sạch trước khi ăn sau buổi tập.',
            ],
            61 => [
                '- Thời gian biểu giúp phân bổ hợp lý giữa học tập, nghỉ ngơi và vui chơi.',
                '- Ưu tiên làm việc vừa quan trọng vừa gấp trước, ví dụ bài kiểm tra ngày mai.',
                '- Gợi ý phân bổ: sáng học tập trung, chiều vận động thể thao, tối ôn bài và chuẩn bị cho ngày mai.',
                '- Lập thời gian biểu và tuân thủ mỗi ngày giúp hình thành thói quen tốt.',
                '- Tránh lướt điện thoại khi học và thói quen nước đến chân mới nhảy.',
            ],
            63 => [
                '- Khi bạn trình bày ý kiến: lắng nghe chăm chú và không ngắt lời.',
                '- Lắng nghe hết ý và cảm ơn là giao tiếp tốt; ngắt lời, chê bai là thiếu tôn trọng.',
                '- Làm việc nhóm: phân công theo khả năng để mỗi bạn phát huy điểm mạnh.',
                '- Hoàn thành đúng phần việc của mình và sẵn sàng hỗ trợ bạn khi cần.',
                '- Nói năng lịch sự, tôn trọng ý kiến khác biệt của các thành viên trong nhóm.',
            ],
            65 => [
                '- Ngồi trên xe máy, xe đạp điện phải đội mũ bảo hiểm đạt chuẩn và cài quai chắc chắn.',
                '- Biển tròn viền đỏ là biển cấm, tam giác viền đỏ là biển cảnh báo, tròn nền xanh là biển hiệu lệnh.',
                '- Qua đường nơi không có đèn tín hiệu: quan sát kỹ hai hướng, đợi xe dừng hẳn mới qua.',
                '- Đi đúng phần đường quy định, không lạng lách, không vượt đèn đỏ.',
                '- Mũ bảo hiểm bảo vệ đầu khi có va chạm — thói quen đơn giản cứu sống.',
            ],
            67 => [
                '- Rác hữu cơ: vỏ rau, thức ăn thừa — có thể ủ làm phân bón cho cây.',
                '- Rác tái chế: chai nhựa, giấy báo — thu gom để tái chế thành sản phẩm mới.',
                '- Rác nguy hại: pin cũ, bóng đèn hỏng — phải thu gom riêng, không vứt bừa bãi.',
                '- Phân loại rác tại nguồn giúp xử lý rác hiệu quả, bảo vệ môi trường.',
                '- Mỗi hành động nhỏ như bỏ rác đúng nơi đều góp phần giữ môi trường xanh sạch.',
            ],
            68 => [
                '- Bác sĩ: khám chữa bệnh, chăm sóc sức khỏe cộng đồng — làm việc chủ yếu tại bệnh viện.',
                '- Giáo viên: dạy học, giáo dục học sinh — cần yêu thương và kiên nhẫn.',
                '- Kỹ sư: thiết kế, xây dựng công trình và máy móc — thuộc nhóm sản xuất, xây dựng.',
                '- Nông dân: trồng trọt, chăn nuôi — cung cấp lương thực cho xã hội.',
                '- Mỗi nghề đều có giá trị và đóng góp riêng, đáng được tôn trọng như nhau.',
            ],
            69 => [
                '- Chọn nghề dựa vào sở thích và năng lực của bản thân, không chạy theo phong trào.',
                '- Ước mơ cần hành động: muốn làm bác sĩ thì học giỏi Sinh, Hóa ngay từ bây giờ.',
                '- Học chăm và tìm hiểu nghề giúp đạt ước mơ; lười học và bỏ cuộc cản trở ước mơ.',
                '- Lập kế hoạch học tập cụ thể từng năm để tiến gần hơn đến ước mơ.',
                '- Trao đổi với thầy cô, cha mẹ để được định hướng nghề nghiệp phù hợp.',
            ],
            77 => [
                '- Có 7 nốt nhạc cơ bản: Đồ, Rê, Mi, Fa, Sol, La, Si.',
                '- Thứ tự 7 nốt nhạc: Đồ – Rê – Mi – Fa – Sol – La – Si, sau nốt Si lại quay về nốt Đồ cao hơn.',
                '- Nốt Đồ là nốt đầu tiên, nốt Si là nốt cuối cùng trong thang nhạc cơ bản.',
                '- Nốt càng về sau trong thứ tự thì cao độ càng cao.',
                '- Học thuộc tên và thứ tự 7 nốt nhạc là nền tảng để đọc nhạc.',
            ],
            78 => [
                '- Cao độ cho biết âm thanh cao hay thấp; nốt nằm càng cao trên khuông nhạc thì cao độ càng cao.',
                '- Trường độ cho biết âm thanh dài hay ngắn: nốt tròn ngân dài nhất, nốt móc đơn ngân ngắn.',
                '- Bốn hình nốt cơ bản: tròn, trắng, đen, móc đơn — mỗi nốt sau ngắn bằng một nửa nốt trước.',
                '- Đọc nhạc cần kết hợp cả cao độ (nốt nào) và trường độ (ngân bao lâu).',
                '- Luyện nghe phân biệt cao – thấp, dài – ngắn giúp cảm thụ âm nhạc tốt hơn.',
            ],
            79 => [
                '- Số chỉ nhịp gồm hai số: số trên chỉ số phách trong một ô nhịp, số dưới chỉ nốt đen là đơn vị phách.',
                '- Nhịp 2/4: mỗi ô nhịp có 2 phách — khỏe khoắn, hợp với hành khúc.',
                '- Nhịp 3/4: mỗi ô nhịp có 3 phách — uyển chuyển, hợp với điệu valse nhẹ nhàng.',
                '- Ô nhịp là đoạn nhạc nằm giữa hai vạch nhịp.',
                '- Nhận biết số chỉ nhịp giúp đánh đúng nhịp khi hát và chơi nhạc.',
            ],
            80 => [
                '- Dấu lặng chỉ khoảng nghỉ — nơi người hát, người chơi nhạc tạm ngưng phát ra âm thanh.',
                '- Mỗi loại nốt đều có dấu lặng tương ứng: lặng tròn, lặng trắng, lặng đen.',
                '- Lặng tròn nghỉ bằng một nốt tròn, lặng đen nghỉ bằng một nốt đen.',
                '- Dấu lặng càng lớn thì thời gian nghỉ càng dài.',
                '- Tôn trọng dấu lặng giúp bản nhạc có nhịp điệu đúng, không bị vội vàng.',
            ],
            81 => [
                '- Đàn bầu chỉ có duy nhất 1 dây — nhạc cụ độc đáo nhất của Việt Nam; một tay gảy, một tay rung cần đàn.',
                '- Sáo thuộc bộ hơi (thổi); đàn tranh, đàn bầu thuộc bộ dây; trống cơm thuộc bộ gõ.',
                '- Nhạc cụ dân tộc chia thành các bộ: dây, hơi, gõ.',
                '- Mỗi nhạc cụ có cách chơi riêng tạo nên âm sắc đặc trưng.',
                '- Tìm hiểu nhạc cụ dân tộc giúp thêm yêu và tự hào về văn hóa Việt Nam.',
            ],
            82 => [
                '- Muốn hát đúng giai điệu, việc đầu tiên là nghe kỹ giai điệu mẫu.',
                '- Lấy hơi ở chỗ dấu lặng hoặc cuối câu nhạc; ngắt hơi giữa chừng làm sai giai điệu.',
                '- Giữ đúng nhịp khi hát, không hát nhanh chậm tùy ý.',
                '- Hát đúng cao độ từng nốt, chú ý những chỗ lên cao, xuống thấp.',
                '- Luyện tập thường xuyên với bài hát vừa sức giúp hát ngày càng hay.',
            ],
            215 => [
                '- 7 nốt nhạc cơ bản: Đồ, Rê, Mi, Pha, Son, La, Si.',
                '- Ký hiệu quốc tế: Đồ = C, Rê = D, Mi = E, Pha = F, Son = G, La = A, Si = B.',
                '- Trong 7 nốt: Đồ – Rê – Mi trầm hơn; Son – La – Si bổng hơn.',
                '- Hình nốt cơ bản: tròn, trắng, đen, móc đơn — thể hiện độ dài ngắn của âm thanh.',
                '- Nốt Đồ là nốt đầu tiên trong thang nhạc 7 nốt.',
            ],
            216 => [
                '- Khuông nhạc gồm 5 dòng kẻ ngang song song, tạo thành 4 khe nhạc ở giữa.',
                '- Khóa Son đặt ở đầu khuông nhạc, xác định vị trí các nốt nhạc.',
                '- Với khóa Son, các nốt trên dòng kẻ: dòng 1 Mi, dòng 2 Son, dòng 3 Si, dòng 4 Rê, dòng 5 Pha.',
                '- Các nốt trong khe: khe 1 Pha, khe 2 La, khe 3 Đồ, khe 4 Mi.',
                '- Nốt nhạc viết trên dòng kẻ hoặc trong khe — đọc đúng vị trí là đọc đúng tên nốt.',
            ],
            217 => [
                '- Quãng là khoảng cách cao độ giữa hai nốt nhạc, tính bằng số bậc.',
                '- Cách tính quãng: đếm số bậc từ nốt thấp đến nốt cao (Đồ = 1, Rê = 2, Mi = 3...).',
                '- Đồ – Mi là quãng 3 (đếm 3 bậc: Đồ, Rê, Mi); Đồ – Son là quãng 5.',
                '- Quãng 2, 3 là quãng hẹp (hai nốt gần nhau); quãng 5, 8 là quãng rộng (hai nốt xa nhau).',
                '- Quãng 8 là quãng tám: hai nốt cùng tên, nốt sau cao hơn nốt trước một quãng tám.',
            ],
            218 => [
                '- Dấu thăng (#) đặt trước nốt nào thì nâng nốt đó lên nửa cung.',
                '- Dấu giáng (b) đặt trước nốt nào thì hạ nốt đó xuống nửa cung.',
                '- Dấu bình (♮) hủy bỏ thăng hoặc giáng, trả nốt về cao độ tự nhiên.',
                '- Ba dấu hóa cơ bản: thăng nâng, giáng hạ, bình hủy.',
                '- Âm giai Đô trưởng gồm 8 nốt: Đồ – Rê – Mi – Pha – Son – La – Si – Đố.',
            ],
            219 => [
                '- Số trên của số chỉ nhịp cho biết mỗi ô nhịp có bao nhiêu phách (2/4 có 2 phách, 3/4 có 3 phách).',
                '- Số dưới cho biết giá trị mỗi phách: số 4 nghĩa là nốt đen là đơn vị phách.',
                '- Nhịp 2/4 khỏe khoắn hợp hành khúc; nhịp 3/4 uyển chuyển hợp điệu valse.',
                '- Dấu lặng tròn, trắng, đen tương ứng với thời gian nghỉ của nốt tròn, trắng, đen.',
                '- Đọc đúng số chỉ nhịp và dấu lặng là nền tảng để đọc bản nhạc.',
            ],
            220 => [
                '- Nhịp 4/4: mỗi ô nhịp có 4 phách đen; còn được ký hiệu bằng chữ C.',
                '- Dấu chấm dôi đặt sau nốt nhạc làm tăng thêm một nửa giá trị của nốt đó.',
                '- Nốt trắng chấm dôi = 2 + 1 = 3 phách; nốt đen chấm dôi = 1 + 0,5 = 1,5 phách.',
                '- Trường độ các nốt (đơn vị nốt đen): tròn 4, trắng 2, đen 1, móc đơn 1/2, móc kép 1/4.',
                '- Ô nhịp 2/4 chứa tối đa 4 nốt móc đơn (2 phách, mỗi phách 2 móc đơn).',
            ],
            221 => [
                '- Nhịp đơn: mỗi phách chia thành 2 phần bằng nhau (mẫu số thường là 4 như 2/4, 3/4, 4/4).',
                '- Nhịp kép: mỗi phách chia thành 3 phần bằng nhau (mẫu số thường là 8 như 6/8, 9/8).',
                '- Nhịp 6/8 là nhịp kép, có 2 phách; mỗi phách bằng một nốt đen chấm dôi (3 nốt móc đơn).',
                '- Phân biệt nhịp đơn – kép qua cách chia phách chứ không chỉ nhìn số chỉ nhịp.',
                '- Nhịp kép thường gợi cảm giác nhún nhảy, uyển chuyển.',
            ],
            222 => [
                '- Trường độ các nốt (đơn vị nốt đen): tròn 4, trắng 2, đen 1, móc đơn 1/2, móc kép 1/4.',
                '- Nốt móc kép = một nửa nốt móc đơn = 1/4 phách.',
                '- Ô nhịp 2/4 = 2 phách, chứa tối đa 4 nốt móc đơn.',
                '- Đếm phách đều khi đọc nhạc giúp giữ đúng nhịp của bản nhạc.',
                '- Dấu diễn cảm cơ bản (to – nhỏ, nhanh – chậm) giúp bản nhạc có hồn hơn.',
            ],
            223 => [
                '- Đàn bầu là nhạc cụ độc đáo chỉ có 1 dây của Việt Nam, âm thanh réo rắt đặc biệt.',
                '- Đàn tranh (đàn thập lục) có 16 dây, gảy bằng móng tay.',
                '- Nhóm dây gảy: đàn bầu, đàn tranh, đàn nguyệt, đàn tỳ bà — dùng tay hoặc móng gảy dây.',
                '- Nhóm dây kéo: đàn nhị, đàn gáo — dùng vĩ kéo trên dây.',
                '- Nhận biết nhạc cụ dây qua số dây và hình dáng mặt đàn.',
            ],
            224 => [
                '- Nhóm hơi: sáo (làm bằng trúc, âm thanh trong), kèn bầu — dùng hơi thổi.',
                '- Nhóm gõ: trống cơm, phách, cồng chiêng — dùng tay hoặc dùi tác động.',
                '- Không gian văn hóa cồng chiêng Tây Nguyên là di sản văn hóa phi vật thể của nhân loại (UNESCO).',
                '- Mỗi nhạc cụ có cách phát ra âm thanh riêng: thổi, gảy, kéo, gõ.',
                '- Nhạc cụ dân tộc là tài sản văn hóa quý báu cần giữ gìn.',
            ],
            225 => [
                '- Dân ca quan họ Bắc Ninh được UNESCO công nhận là di sản văn hóa phi vật thể năm 2009.',
                '- Chèo là loại hình sân khấu dân gian Bắc Bộ, kết hợp hát, múa và diễn xuất.',
                '- Ca trù là nghệ thuật hát thơ đặc sắc của miền Bắc.',
                '- Đờn ca tài tử là nghệ thuật đờn – hát của Nam Bộ.',
                '- Mỗi loại hình có không gian diễn xướng riêng theo vùng miền: quan họ, chèo (Bắc); hò Huế (Trung); đờn ca tài tử (Nam).',
            ],
            226 => [
                '- Nhạc cụ phương Tây tiêu biểu: violin, piano, trumpet, flute.',
                '- Violin có 4 dây, dùng vĩ kéo — đứng đầu bộ dây trong dàn nhạc giao hưởng.',
                '- Bốn nhóm nhạc cụ phương Tây: dây, phím, kèn đồng, kèn gỗ.',
                '- Dàn nhạc giao hưởng gồm nhiều nhạc cụ phương Tây, do nhạc trưởng chỉ huy bằng đũa chỉ huy.',
                '- Dàn nhạc dân tộc gồm nhạc cụ truyền thống Việt Nam như đàn bầu, đàn tranh, sáo.',
            ],
            227 => [
                '- Ba màu cơ bản: đỏ, vàng, lam — không pha được từ màu khác mà có.',
                '- Ba màu thứ cấp: cam (đỏ + vàng), lục (vàng + lam), tím (đỏ + lam).',
                '- Đỏ + trắng = hồng: thêm trắng làm màu sáng và nhạt dần.',
                '- Biết pha màu giúp tạo ra nhiều màu mới từ bộ màu hạn chế.',
                '- Nên thử màu trên giấy nháp trước khi tô vào tranh chính.',
            ],
            228 => [
                '- Màu nóng: đỏ, cam, vàng — gợi cảm giác ấm áp, sôi động, vui tươi.',
                '- Màu lạnh: lam, lục, tím — gợi cảm giác mát mẻ, yên tĩnh, trầm lắng.',
                '- Màu lam (xanh dương) gợi cảm giác mát mẻ nhất, như nước và bầu trời.',
                '- Màu sắc diễn tả được cảm xúc: vui dùng gam nóng, buồn dùng gam lạnh.',
                '- Cùng một vật, đổi gam màu sẽ đổi hẳn cảm xúc của bức tranh.',
            ],
            229 => [
                '- Thêm trắng làm màu nhạt dần, thêm đen làm màu đậm dần — gọi là sắc độ của màu.',
                '- Đỏ + trắng = hồng là ví dụ điển hình của việc tạo sắc độ nhạt.',
                '- Cặp màu tương phản nằm đối diện nhau trên vòng tròn màu: đỏ – lục, vàng – tím, cam – lam.',
                '- Cặp màu tương đồng nằm kề nhau trên vòng tròn màu, ví dụ đỏ – cam.',
                '- Dùng màu tương phản để tạo điểm nhấn, dùng màu tương đồng để tạo sự hài hòa.',
            ],
            230 => [
                '- Màu chủ đạo chiếm diện tích lớn nhất, quyết định cảm xúc chung của bức tranh.',
                '- Điểm nhấn màu là mảng màu tương phản nhỏ, dẫn mắt người xem đến chi tiết quan trọng.',
                '- Tranh Đông Hồ dùng màu từ nguyên liệu tự nhiên nên có sắc trầm ấm, mộc mạc.',
                '- Phối hợp màu chủ đạo, màu nền và điểm nhấn tạo nên bố cục màu hoàn chỉnh.',
                '- Xác định màu chủ đạo trước khi tô giúp tranh có định hướng rõ ràng.',
            ],
            231 => [
                '- Nét thẳng gợi sự cứng cáp, chắc chắn; dùng vẽ vật cứng, công trình, nhà cửa.',
                '- Nét cong gợi sự mềm mại, uyển chuyển như sóng nước, cầu vồng; dùng vẽ vật mềm, uốn lượn.',
                '- Nét gấp khúc (zigzag) gợi sự mạnh mẽ, gấp gáp như tia chớp.',
                '- Nét đứt gợi sự nhẹ nhàng, xa xăm; dùng vẽ vật ở xa, mờ ảo.',
                '- Trong vẽ kỹ thuật, mỗi loại nét có quy ước riêng cần tuân thủ đúng.',
            ],
            232 => [
                '- Bố cục là cách sắp xếp các hình mảng trong tranh, quyết định nhịp điệu và cảm xúc.',
                '- Bố cục đối xứng: hai nửa tranh giống nhau qua trục giữa, ví dụ mặt người, con bướm.',
                '- Bố cục tự do: sắp xếp phóng khoáng không theo trục đối xứng, ví dụ dòng sông, đám mây.',
                '- Điểm nhấn dẫn mắt người xem đến chi tiết quan trọng nhất của bức tranh.',
                '- Đường chân trời trong tranh phong cảnh thường đặt ở 1/3 chiều cao tranh để cân đối.',
            ],
            233 => [
                '- Bốn khối cơ bản: cầu, trụ, hộp, nón — mọi vật thể đều cấu tạo từ các khối này.',
                '- Quả cam, quả địa cầu gần với khối cầu; lon sữa bò gần với khối trụ.',
                '- Phối cảnh: vật ở gần vẽ to, rõ nét; vật ở xa vẽ nhỏ, mờ dần.',
                '- Ánh sáng tạo vùng sáng – tối trên khối, giúp khối có chiều sâu và thật hơn.',
                '- Khi vẽ theo mẫu, xác định khối cơ bản của vật trước rồi mới vẽ chi tiết.',
            ],
            234 => [
                '- Họa tiết trang trí thường lặp lại có quy luật, tạo nhịp điệu cho bố cục.',
                '- Trung tâm mặt trống đồng Đông Sơn là ngôi sao nhiều cánh tượng trưng cho mặt trời.',
                '- Họa tiết từ thiên nhiên: hoa lá, con vật được cách điệu; họa tiết hình học: đường nét, hình khối.',
                '- Mỗi chất liệu có kỹ thuật tạo họa tiết riêng như khắc, thêu, vẽ.',
                '- Hoa văn trống đồng Đông Sơn là di sản văn hóa tiêu biểu của người Việt cổ.',
            ],
            235 => [
                '- Làng tranh Đông Hồ thuộc huyện Thuận Thành, tỉnh Bắc Ninh.',
                '- Giấy điệp: vỏ sò điệp giã nhỏ, trộn hồ rồi quét lên giấy dó tạo độ óng ánh.',
                '- Màu vẽ từ nguyên liệu tự nhiên nên tranh có sắc trầm ấm, bền màu.',
                '- Tranh Đám cưới chuột châm biếm thói hối lộ của quan lại phong kiến xưa.',
                '- Nghề làm tranh đòi hỏi sự kiên nhẫn, tỉ mỉ qua nhiều công đoạn.',
            ],
            236 => [
                '- Tranh Hàng Trống: in ván lấy nét đen rồi nghệ nhân tô màu bằng tay nên mềm mại.',
                '- Tranh Kim Hoàng in trên giấy hồng điều đỏ — nét riêng không dòng tranh nào có.',
                '- Tranh Đông Hồ in ván khắc gỗ trên giấy điệp, màu từ nguyên liệu tự nhiên.',
                '- Mỗi dòng tranh có kỹ thuật, chất liệu và phong cách riêng.',
                '- Phân biệt các dòng tranh qua cách in, cách tô màu và loại giấy sử dụng.',
            ],
            237 => [
                '- Tranh Làng Sình (Phú Vang, Thừa Thiên Huế) chủ yếu là tranh thờ cúng trong gia đình.',
                '- Tranh kính Nam Bộ vẽ trên mặt kính với màu sắc rực rỡ.',
                '- Miền Bắc có tranh Đông Hồ, Hàng Trống; miền Trung có tranh Làng Sình; miền Nam có tranh kính.',
                '- Mỗi vùng miền có đề tài, chất liệu gắn với đời sống văn hóa địa phương.',
                '- Tranh dân gian phản ánh ước mơ, tín ngưỡng và đời sống của người dân từng vùng.',
            ],
            238 => [
                '- Nghệ nhân là người tinh thông và truyền dạy nghề truyền thống — báu vật sống của làng nghề.',
                '- Thách thức lớn nhất hiện nay: nghệ nhân cao tuổi, giới trẻ ít theo nghề, tranh đứng trước nguy cơ mai một.',
                '- Bảo tồn tranh dân gian: truyền nghề cho thế hệ trẻ, quảng bá đến du khách, đưa vào trường học.',
                '- Ứng dụng hiện đại: đưa họa tiết dân gian vào thiết kế thời trang, bao bì, quà lưu niệm.',
                '- Mỗi hành động ủng hộ tranh dân gian đều góp phần giữ gìn di sản văn hóa dân tộc.',
            ],
            239 => [
                '- Việc đầu tiên trước khi chơi thể thao là khởi động 5–10 phút: xoay khớp, chạy nhẹ, ép dẻo.',
                '- Kiểm tra sân bãi, dụng cụ trước khi chơi để loại bỏ nguy cơ như đá sỏi, mặt sân trơn.',
                '- Khởi động trước buổi tập và thả lỏng nhẹ sau buổi tập là trình tự đúng.',
                '- Mang giày thể thao phù hợp, trang phục gọn gàng khi vận động.',
                '- An toàn là nguyên tắc đầu tiên của mọi hoạt động thể thao.',
            ],
            240 => [
                '- Khi chạy, hai tay đánh nhịp ngược với chân giúp giữ thăng bằng và tăng tốc.',
                '- Khi nhảy từ trên cao xuống, tiếp đất bằng mũi chân rồi khụy gối để hấp thụ lực.',
                '- Thở đều khi vận động: hít vào bằng mũi, thở ra bằng miệng.',
                '- Tư thế đúng giúp vận động hiệu quả và tránh chấn thương khớp gối.',
                '- Không nín thở khi gắng sức; thở nhịp nhàng theo từng động tác.',
            ],
            241 => [
                '- Chuột rút là hiện tượng cơ co cứng đột ngột, đau nhói — cần dừng lại, kéo giãn nhẹ và bổ sung nước.',
                '- Nguyên tắc sơ cứu RICE: Rest (nghỉ ngơi), Ice (chườm lạnh), Compression (băng ép), Elevation (kê cao).',
                '- Khi bong gân: chườm lạnh trước, không chườm nóng ngay và không tự nắn khớp.',
                '- Trật khớp phải đến cơ sở y tế, tuyệt đối không tự nắn chỉnh tại chỗ.',
                '- Khởi động kỹ và tập đúng kỹ thuật là cách phòng tránh chấn thương tốt nhất.',
            ],
            242 => [
                '- Sức nhanh: chạy cự ly ngắn 60m, 100m — bứt tốc tối đa trong thời gian ngắn.',
                '- Sức mạnh: chống đẩy, nâng tạ — rèn cơ tay, vai, ngực, chân khỏe hơn.',
                '- Sức bền: chạy dài, bơi dài — duy trì vận động lâu mà không mệt.',
                '- Sức dẻo: ép dẻo, gập người — tăng linh hoạt cho khớp và cơ.',
                '- Chọn bài tập đúng với tố chất muốn phát triển; kết hợp nhiều tố chất để cơ thể phát triển toàn diện.',
            ],
            243 => [
                '- Bóng đá 11 người: mỗi đội có 11 cầu thủ trên sân khi thi đấu.',
                '- Quả phạt đền (penalty) được đá từ chấm 11m khi phạm lỗi trong vòng cấm địa.',
                '- Thẻ vàng là cảnh cáo, thẻ đỏ là truất quyền thi đấu ngay lập tức.',
                '- Trận đấu có 2 hiệp; đội ghi nhiều bàn thắng hơn thì thắng trận.',
                '- Luật việt vị khuyến khích lối chơi tấn công đẹp mắt, chống việc ăn sẵn gần khung thành.',
            ],
            244 => [
                '- Dẫn bóng rổ: đập bóng bằng một tay, có thể đổi tay khi di chuyển.',
                '- Cầm bóng chỉ được chạy tối đa 2 bước; quá số bước là lỗi chạy bước.',
                '- Dẫn bóng hai tay cùng lúc rồi dẫn tiếp là lỗi hai lần dẫn bóng.',
                '- Ném trong vòng cung 3 điểm được 2 điểm; ngoài vòng cung được 3 điểm; ném phạt được 1 điểm.',
                '- Khi dẫn bóng cần giữ bóng chắc, mắt quan sát đồng đội và đối phương.',
            ],
            245 => [
                '- Bóng chuyền trong nhà: mỗi đội có 6 người trên sân.',
                '- Mỗi đội được chạm bóng tối đa 3 lần trước khi đưa bóng sang sân đối phương.',
                '- Thứ tự chạm bóng thường là: đỡ bóng, chuyền hai rồi đập bóng.',
                '- Chạm lưới khi bóng còn trong cuộc là lỗi, đối phương được điểm.',
                '- Mỗi set đánh đến 25 điểm (hơn đối phương 2 điểm); set quyết định đánh đến 15 điểm.',
            ],
            246 => [
                '- Cầu lông tính điểm rally: thắng set khi đạt 21 điểm và hơn đối phương 2 điểm (tối đa 30 điểm).',
                '- Thắng 2 trong 3 set thì thắng chung cuộc cả trận.',
                '- Giao cầu phải đánh chéo sân sang ô đối diện của đối phương.',
                '- Cầu chạm vạch vẫn tính là trong sân, không phải lỗi.',
                '- Nắm vững kỹ thuật giao cầu và di chuyển là nền tảng chơi cầu lông tốt.',
            ],
            247 => [
                '- Bốn nhóm chất chính: bột đường, chất đạm, chất béo, vitamin và khoáng chất.',
                '- Bột đường (cơm, bánh mì, khoai) là nguồn năng lượng chính cho cơ thể vận động.',
                '- Chất đạm (thịt, trứng, sữa, đậu) xây dựng và phục hồi cơ bắp.',
                '- Rau củ cung cấp vitamin, chất xơ giúp tiêu hóa tốt và tăng sức đề kháng.',
                '- Bữa ăn đủ 4 nhóm chất mới cân đối, đảm bảo năng lượng cho tập luyện.',
            ],
            248 => [
                '- Sau khi tập ra nhiều mồ hôi: tắm rửa sạch sẽ, thay đồ khô để tránh cảm lạnh và viêm da.',
                '- Không dùng chung khăn mặt, bình nước để tránh lây bệnh da liễu, cúm.',
                '- Giữ sân bãi và dụng cụ tập luyện sạch sẽ sau khi sử dụng.',
                '- Bỏ rác đúng nơi quy định, giữ vệ sinh chung nơi tập luyện.',
                '- Vệ sinh tốt bảo vệ sức khỏe của bản thân và cộng đồng.',
            ],
            249 => [
                '- Công thức ước tính nhịp tim tối đa: 220 trừ đi số tuổi (ví dụ 15 tuổi thì khoảng 205 nhịp/phút).',
                '- Khi vận động, nhịp tim và nhịp thở tăng lên để cung cấp ôxy cho cơ bắp.',
                '- Tim, phổi, máu và cơ phối hợp nhịp nhàng trong mọi hoạt động vận động.',
                '- Thở đúng khi vận động: hít sâu bằng mũi, thở ra đều bằng miệng.',
                '- Theo dõi nhịp tim giúp tập luyện đúng cường độ, tránh vận động quá sức.',
            ],
            250 => [
                '- Doping là chất cấm dùng để gian lận thành tích trong thể thao.',
                '- Vận động viên dương tính với doping bị phạt nặng: cấm thi đấu, tước danh hiệu.',
                '- Rượu bia làm giảm phản xạ, sức bền và khả năng tập trung khi thi đấu.',
                '- Thuốc lá gây hại phổi và tim mạch, làm giảm thể lực nghiêm trọng.',
                '- Nói không với chất kích thích để bảo vệ sức khỏe và thi đấu công bằng.',
            ],
            251 => [
                '- Nên học tập trung 25–30 phút rồi nghỉ 5 phút giúp não hồi phục, nhớ lâu hơn.',
                '- Ưu tiên việc quan trọng trước là nguyên tắc cốt lõi của quản lý thời gian.',
                '- Lập thời gian biểu học tập cá nhân cho từng ngày, từng tuần.',
                '- Bắt đầu với việc nhỏ, dễ làm để tạo đà hoàn thành công việc.',
                '- Theo dõi việc đã làm mỗi ngày giúp điều chỉnh kế hoạch kịp thời.',
            ],
            252 => [
                '- Lắng nghe tích cực: chăm chú, không ngắt lời, gật đầu và đặt câu hỏi làm rõ.',
                '- Ngắt lời người khác là thiếu tôn trọng, làm mất thiện cảm trong giao tiếp.',
                '- Làm việc nhóm hiệu quả cần phân công rõ ràng: ai làm gì, khi nào xong.',
                '- Nói năng lịch sự, dùng lời cảm ơn và xin lỗi đúng lúc.',
                '- Chia sẻ ý kiến thẳng thắn nhưng tôn trọng giúp cả nhóm cùng tiến bộ.',
            ],
            253 => [
                '- Khi đang rất tức giận: dừng lại và hít thở thật sâu để cơn giận lắng xuống.',
                '- Đếm từ 1 đến 10 giúp kiềm chế bản thân trước khi nói hoặc hành động.',
                '- Nhận diện cảm xúc qua biểu hiện bên ngoài: vui, buồn, giận, sợ hãi.',
                '- Cảm xúc tích cực: vui vẻ, yêu thương, biết ơn; cảm xúc tiêu cực: giận dữ, buồn bã, lo lắng.',
                '- Cảm xúc tiêu cực cũng cần được chia sẻ với người tin cậy, không nên giấu kín.',
            ],
            254 => [
                '- Bước 1: xác định rõ vấn đề là gì — xác định đúng là đã giải quyết được một nửa.',
                '- Bước 2: tìm nguyên nhân gây ra vấn đề.',
                '- Bước 3: liệt kê các giải pháp có thể thực hiện.',
                '- Bước 4: so sánh các giải pháp rồi chọn cách tốt nhất.',
                '- Bước 5: thực hiện giải pháp đã chọn và đánh giá kết quả.',
            ],
            255 => [
                '- Đi xe máy, xe đạp điện bắt buộc đội mũ bảo hiểm đạt chuẩn bảo vệ đầu.',
                '- Đi bên phải theo chiều đi của mình, đúng phần đường quy định.',
                '- Qua đường ở vạch kẻ (vạch ngựa vằn) — nơi xe cộ phải nhường người đi bộ.',
                '- Tuân thủ tín hiệu đèn giao thông, tuyệt đối không vượt đèn đỏ.',
                '- Không dàn hàng ngang, không lạng lách khi tham gia giao thông.',
            ],
            256 => [
                '- Số điện thoại khẩn cấp: 114 cứu hỏa, 115 cấp cứu, 113 công an, 111 bảo vệ trẻ em.',
                '- Khi cháy trong tòa nhà: bình tĩnh, cúi thấp người tránh khói độc, đi thang bộ — tuyệt đối không đi thang máy.',
                '- Phát hiện cháy phải báo ngay cho người lớn và gọi 114.',
                '- Khi thoát hiểm không quay lại lấy đồ đạc, tính mạng là quan trọng nhất.',
                '- Học cách dùng bình chữa cháy mini để dập đám cháy nhỏ khi đảm bảo an toàn.',
            ],
            257 => [
                '- 3R trong bảo vệ môi trường: Reduce (giảm thiểu), Reuse (tái sử dụng), Recycle (tái chế).',
                '- Phân loại rác thành 3 nhóm: hữu cơ, tái chế và nguy hại.',
                '- Túi nilon khó phân hủy, gây ô nhiễm đất và đại dương — hạn chế dùng, thay bằng túi vải.',
                '- Chai nhựa, giấy báo tái chế được thành nhiều sản phẩm mới.',
                '- Mỗi người giảm một túi nilon mỗi ngày là góp phần bảo vệ môi trường.',
            ],
            258 => [
                '- Không chia sẻ công khai địa chỉ nhà, số điện thoại, trường lớp — người lạ có thể lợi dụng.',
                '- Đặt mật khẩu mạnh: dài, khó đoán, không dùng thông tin cá nhân dễ đoán.',
                '- Cảnh giác với tin nhắn lừa đảo và đường link lạ — không bấm vào khi chưa chắc chắn.',
                '- Bị bắt nạt trên mạng: chặn, báo cáo và kể ngay với người lớn tin cậy.',
                '- Thông tin cá nhân chỉ chia sẻ với người thực sự tin cậy.',
            ],
            259 => [
                '- Nhóm nghề y tế: bác sĩ, y tá — khám chữa bệnh, chăm sóc sức khỏe.',
                '- Nhóm nghề giáo dục: giáo viên — dạy học, giáo dục thế hệ trẻ.',
                '- Nhóm nghề kỹ thuật: kỹ sư — thiết kế, xây dựng, chế tạo máy móc.',
                '- Nhóm nghề công nghệ thông tin: lập trình viên — viết phần mềm, ứng dụng.',
                '- Mỗi nhóm nghề có công việc đặc trưng và yêu cầu năng lực riêng.',
            ],
            260 => [
                '- Sở thích là điều mình thích làm; năng lực là điều mình làm tốt; điểm mạnh cần được phát huy.',
                '- Ai cũng có điểm mạnh và điểm yếu — quan trọng là nhận ra chúng.',
                '- Chọn nghề theo năng lực và đam mê, không chạy theo phong trào hay bạn bè.',
                '- Điểm yếu có thể cải thiện bằng rèn luyện kiên trì mỗi ngày.',
                '- Hiểu rõ bản thân là bước đầu tiên để chọn nghề phù hợp.',
            ],
            261 => [
                '- Sau lớp 9 có nhiều hướng đi: thi vào THPT, học trung cấp nghề, vừa học văn hóa vừa học nghề.',
                '- Trường trung cấp nghề đào tạo nghề cụ thể như điện, may, nấu ăn, sửa xe.',
                '- Chọn hướng đi căn cứ vào năng lực học tập, sở thích và điều kiện gia đình.',
                '- Học nghề sớm giúp có tay nghề vững, sớm đi làm nếu phù hợp.',
                '- Dù chọn hướng nào cũng cần học tập nghiêm túc và không ngừng nâng cao tay nghề.',
            ],
            262 => [
                '- AI (Artificial Intelligence) là trí tuệ nhân tạo, đang thay đổi nhiều nghề nghiệp hiện nay.',
                '- Công nghệ sinh ra nhiều nghề mới, nhưng nghề truyền thống vẫn giữ giá trị riêng.',
                '- Nhóm nghề khó bị AI thay thế nhất: sáng tạo, cảm xúc, chăm sóc con người.',
                '- Kỹ năng của tương lai: công nghệ số, ngoại ngữ, tư duy sáng tạo và học suốt đời.',
                '- Chủ động học hỏi công nghệ để không bị tụt hậu trong thời đại số.',
            ],
            383 => [
                '- Hợp âm ba (triad) gồm 3 nốt xếp chồng theo quãng 3: nốt gốc, nốt bậc 3 và nốt bậc 5.',
                '- Hợp âm trưởng = quãng 3 trưởng + quãng 5 đúng (ví dụ Đô trưởng gồm C – E – G).',
                '- Hợp âm thứ = quãng 3 thứ + quãng 5 đúng, âm sắc trầm buồn hơn hợp âm trưởng.',
                '- Ký hiệu quốc tế: không có chữ "m" là trưởng (C), có chữ "m" là thứ (Am).',
                '- Hợp âm là nền tảng của đệm hát và hòa âm trong âm nhạc.',
            ],
            384 => [
                '- Ký hiệu quốc tế: A = La, B = Si, C = Đô, D = Rê, E = Mi, F = Fa, G = Sol.',
                '- Vòng hợp âm C – G – Am – F gồm các bậc I – V – vi – IV trong giọng Đô trưởng.',
                '- Hợp âm bậc V của giọng Đô trưởng là Sol, ký hiệu là G.',
                '- Không có chữ "m" là hợp âm trưởng; có chữ "m" là hợp âm thứ (Bb là Si giáng trưởng).',
                '- Vòng hợp âm I – V – vi – IV rất phổ biến trong nhiều bài hát.',
            ],
            385 => [
                '- Khóa Sol còn gọi là khóa Treble, dùng cho giọng cao và tay phải piano.',
                '- Khóa nhạc xác định vị trí các nốt trên khuông nhạc.',
                '- Khuông nhạc chuẩn gồm 5 dòng kẻ và 4 khe.',
                '- Nhịp đơn có mẫu số là 4 (2/4, 3/4, 4/4); nhịp kép có mẫu số là 8 và tử số chia hết cho 3 (6/8, 9/8).',
                '- Đọc đúng khóa nhạc là bước đầu tiên để đọc bản nhạc.',
            ],
            386 => [
                '- Dấu thăng (#) nâng cao độ của nốt lên nửa cung, ví dụ Fa thành Fa thăng.',
                '- Dấu giáng (b) hạ cao độ của nốt xuống nửa cung.',
                '- Dấu bình (♮) trả nốt về cao độ tự nhiên, hủy bỏ thăng hoặc giáng.',
                '- Dấu hóa đặt ở đầu khuông nhạc (bộ khóa) có tác dụng cho toàn bản nhạc.',
                '- Kỹ thuật đọc bản nhạc nhanh: nhận diện cụm nốt quen thuộc thay vì đọc từng nốt rời rạc.',
            ],
            387 => [
                '- Nhạc cách mạng ra đời và phát triển mạnh trong hai cuộc kháng chiến, giai điệu hào hùng, cổ vũ chiến đấu.',
                '- Nhạc tiền chiến lãng mạn, trữ tình, ra đời trước Cách mạng tháng Tám.',
                '- Tiến quân ca được chọn làm Quốc ca của Việt Nam.',
                '- Cả hai dòng nhạc đều có giá trị lịch sử và nghệ thuật lớn.',
                '- Tìm hiểu các dòng nhạc giúp hiểu thêm lịch sử dân tộc qua âm nhạc.',
            ],
            388 => [
                '- Nhạc trữ tình (bolero) có giai điệu chậm, lời ca da diết về tình yêu quê hương, đôi lứa.',
                '- Nhạc trẻ phản ánh đời sống đô thị hiện đại với tiết tấu sôi động.',
                '- Phối khí mới cho chất liệu dân gian: dùng hòa âm và nhạc cụ hiện đại làm mới làn điệu truyền thống.',
                '- Mỗi dòng nhạc phục vụ một nhu cầu thưởng thức khác nhau của khán giả.',
                '- Âm nhạc Việt Nam ngày càng đa dạng, hội nhập mà vẫn giữ bản sắc dân tộc.',
            ],
            389 => [
                '- Nhạc sĩ là người sáng tác: viết giai điệu, lời ca và ý tưởng hòa âm, phối khí.',
                '- Ca sĩ là người thể hiện tác phẩm của nhạc sĩ đến với khán giả.',
                '- Mỗi vai trò là một mắt xích quan trọng trong đời sống âm nhạc.',
                '- Một bài hát hay cần cả sáng tác tốt và thể hiện tốt.',
                '- Ngoài nhạc sĩ và ca sĩ còn có người hòa âm, phối khí góp phần hoàn thiện tác phẩm.',
            ],
            390 => [
                '- Thế hệ tiền chiến đặt nền móng cho tân nhạc — nhạc Việt Nam hiện đại theo lối phương Tây.',
                '- Thế hệ kháng chiến để lại dòng nhạc cách mạng hào hùng.',
                '- Năm 1975 (đất nước thống nhất) là mốc chia các thế hệ nhạc sĩ trước và sau.',
                '- Mỗi thế hệ gắn với một thời kỳ lịch sử và dòng nhạc riêng.',
                '- Các thế hệ nhạc sĩ nối tiếp nhau làm giàu kho tàng âm nhạc Việt Nam.',
            ],
            391 => [
                '- Âm nhạc bác học là dòng nhạc nghệ thuật phương Tây, thường gọi là nhạc cổ điển — chuẩn mực, tinh tế.',
                '- Jazz ra đời ở Mỹ đầu thế kỷ 20 từ cộng đồng người Mỹ gốc Phi, đặc trưng bởi sự tự do, ngẫu hứng.',
                '- Blues có giai điệu trầm buồn, là nguồn gốc của jazz và rock.',
                '- Ba thể loại có mối quan hệ nguồn gốc: blues sinh ra jazz, jazz ảnh hưởng nhiều dòng nhạc hiện đại.',
                '- Thưởng thức các thể loại giúp mở rộng hiểu biết về âm nhạc thế giới.',
            ],
            392 => [
                '- Rock mạnh mẽ với guitar điện, trống và bass là nhạc cụ đặc trưng.',
                '- Pop là nhạc đại chúng: giai điệu dễ nhớ, dễ hát theo, hướng đến đông đảo khán giả.',
                '- Hip-hop gắn với rap và văn hóa đường phố, tiết tấu khỏe khoắn.',
                '- EDM (nhạc điện tử) được tạo ra từ thiết bị điện tử và máy tính, tiết tấu dồn dập.',
                '- Mỗi thể loại có tiết tấu, nhạc cụ và cách thể hiện riêng.',
            ],
            393 => [
                '- Bản giao hưởng (symphony) điển hình gồm 4 chương với tốc độ khác nhau.',
                '- Giao hưởng tôn vinh sức mạnh tập thể của cả dàn nhạc.',
                '- Concerto là cuộc đối thoại giữa nhạc cụ độc tấu và dàn nhạc, tôn vinh cá nhân nghệ sĩ.',
                '- Cả hai đều là đỉnh cao của âm nhạc bác học phương Tây.',
                '- Nghe giao hưởng và concerto giúp cảm nhận chiều sâu của âm nhạc cổ điển.',
            ],
            394 => [
                '- Opera là vở nhạc kịch mà diễn viên hát toàn bộ lời thoại, quy mô hoành tráng.',
                '- Nhạc kịch hiện đại (musical) xen kẽ các đoạn hát và thoại, gần gũi với khán giả hơn opera.',
                '- Nhạc thính phòng là nhạc cho nhóm nhạc cụ nhỏ, biểu diễn trong không gian nhỏ, tinh tế.',
                '- Ba hình thức có quy mô và phong cách khác nhau: hoành tráng, gần gũi, tinh tế.',
                '- Thưởng thức các hình thức sân khấu âm nhạc giúp mở rộng vốn hiểu biết nghệ thuật.',
            ],
            395 => [
                '- Tranh thủy mặc Trung Hoa dùng mực đen pha nước vẽ trên giấy hoặc lụa, phong cách tối giản.',
                '- Thủy là nước, mặc là mực — thủy mặc nghĩa là dùng nước pha mực để vẽ.',
                '- Tranh khắc gỗ ukiyo-e của Nhật Bản in nhiều bản màu, rực rỡ và sinh động.',
                '- Thủy mặc chú trọng ý cảnh và khoảng trống; ukiyo-e chú trọng màu sắc và chi tiết.',
                '- Cả hai đều là đỉnh cao mỹ thuật Đông Á, ảnh hưởng sâu rộng đến nghệ thuật thế giới.',
            ],
            396 => [
                '- Tranh Đông Hồ: in ván khắc gỗ trên giấy điệp quét điệp, làng Đông Hồ, Bắc Ninh.',
                '- Tranh Hàng Trống: in ván lấy nét rồi tô màu bằng tay nên mềm mại.',
                '- Sơn mài dùng nhựa cây sơn ta, qua nhiều lớp mài tạo độ bóng sâu, sang trọng.',
                '- Tranh lụa mềm mại, nhẹ nhàng; tranh khắc gỗ mộc mạc, khỏe khoắn.',
                '- Mỹ thuật truyền thống Việt Nam mộc mạc mà tinh tế, giàu bản sắc dân tộc.',
            ],
            397 => [
                '- Luật frontal của Ai Cập cổ đại: quy tắc tạo hình cứng nhắc — mặt nghiêng, mắt và thân nhìn thẳng.',
                '- Mỹ thuật Ai Cập gắn với tâm linh, phục vụ đời sống sau khi chết của pharaoh.',
                '- Điêu khắc Hy Lạp tôn vinh vẻ đẹp con người với tỷ lệ cân đối, tả thực.',
                '- La Mã kế thừa Hy Lạp, chú trọng tính thực dụng và chân dung tả thực.',
                '- Ba nền mỹ thuật đặt nền móng cho nghệ thuật phương Tây sau này.',
            ],
            398 => [
                '- Phục hưng (Renaissance) hồi sinh văn hóa cổ điển Hy Lạp – La Mã vào thế kỷ 14–16.',
                '- Thành tựu kỹ thuật của hội họa Phục hưng: luật phối cảnh vẽ không gian ba chiều trên mặt phẳng.',
                '- Trường phái Ấn tượng chú trọng cảm xúc ánh sáng, màu sắc tươi sáng, nét vẽ nhanh.',
                '- Nghệ thuật hiện đại phá cách, thể hiện cái tôi và tư duy mới của nghệ sĩ.',
                '- Dòng chảy mỹ thuật phương Tây: cổ điển chuẩn mực, Ấn tượng cảm xúc, hiện đại phá cách.',
            ],
            399 => [
                '- Cân bằng đối xứng: hai bên bố cục giống nhau, tạo cảm giác trang trọng, ổn định.',
                '- Cân bằng bất đối xứng: các yếu tố khác nhau nhưng vẫn hài hòa, tạo cảm giác năng động.',
                '- Tương phản tạo ra bằng sự đối lập rõ rệt: to – nhỏ, đậm – nhạt, nóng – lạnh.',
                '- Điểm nhấn là chi tiết nổi bật nhất, dẫn mắt người xem trong thiết kế.',
                '- Ba nguyên lý nền tảng giúp mọi thiết kế chuyên nghiệp và thu hút.',
            ],
            400 => [
                '- Nhịp điệu thị giác là sự lặp lại có quy luật, tạo chuyển động cho mắt người xem.',
                '- Tỷ lệ vàng khoảng 1:1,618 được coi là tỷ lệ hài hòa, đẹp nhất.',
                '- Tính thống nhất: mọi yếu tố trong thiết kế phải liên kết, phục vụ một ý tưởng chung.',
                '- Khoảng trắng (không gian âm) giúp thiết kế thoáng, dễ đọc và sang trọng.',
                '- Bốn nguyên lý hoàn thiện một thiết kế chuyên nghiệp.',
            ],
            401 => [
                '- Vòng tròn màu chuẩn gồm 12 màu: 3 màu bậc 1, 3 màu bậc 2, 6 màu bậc 3.',
                '- Ba màu bậc 1 (màu gốc): đỏ, vàng, lam — không pha được từ màu khác.',
                '- Màu nóng: đỏ – cam – vàng; màu lạnh: lam – lục – tím.',
                '- Cặp màu bổ túc nằm đối diện nhau trên vòng tròn màu: đỏ – lục, cam – lam, vàng – tím.',
                '- Đọc được vòng tròn màu là nền tảng để phối màu trong thiết kế.',
            ],
            402 => [
                '- Phối đơn sắc: một màu gốc với nhiều sắc độ đậm nhạt — an toàn, tinh tế, dễ dùng.',
                '- Phối tương đồng: các màu kề nhau trên vòng tròn màu — hài hòa, nhẹ nhàng.',
                '- Phối bổ túc: cặp màu đối diện nhau — tương phản mạnh, nổi bật, cần tiết chế khi dùng.',
                '- Mỗi màu gợi tâm lý riêng: đỏ năng động, xanh dương tin cậy, xanh lá tươi mới.',
                '- Chọn công thức phối màu phù hợp với thông điệp muốn truyền tải.',
            ],
            403 => [
                '- Logo là dấu hiệu nhận biết trung tâm của thương hiệu, xuất hiện trên mọi ấn phẩm.',
                '- Các loại logo: logotype (dạng chữ), biểu tượng (dạng hình), kết hợp chữ và hình.',
                '- Nguyên tắc logo tốt: đơn giản, dễ nhớ, dễ nhận biết ở mọi kích cỡ.',
                '- Logo phải thể hiện được tính cách và lĩnh vực hoạt động của thương hiệu.',
                '- Hệ nhận diện thương hiệu gồm logo, màu sắc, font chữ được dùng nhất quán.',
            ],
            404 => [
                '- Poster hiệu quả cần thứ bậc thông tin rõ ràng: tiêu đề nổi bật nhất, chi tiết phụ nhỏ hơn.',
                '- Typography là nghệ thuật sắp đặt và thiết kế chữ, quyết định vẻ đẹp của phần chữ.',
                '- Font serif có chân (trang trọng, cổ điển); font sans-serif không chân (hiện đại, gọn gàng).',
                '- Lưới bố cục giúp sắp xếp các yếu tố ngay hàng thẳng lối, chuyên nghiệp.',
                '- Bốn thành phần của poster hiệu quả: tiêu đề, hình ảnh, thông tin chi tiết và lời kêu gọi hành động.',
            ],
            405 => [
                '- Kiến trúc cổ điển Hy Lạp – La Mã nổi bật với hệ cột và thức cột (Doric, Ionic, Corinthian).',
                '- Kiến trúc Gothic vươn cao lên trời với vòm nhọn và kính màu rực rỡ.',
                '- Kiến trúc hiện đại chú trọng công năng, đường nét đơn giản, vật liệu mới.',
                '- Kiến trúc truyền thống Việt Nam: mái cong, kết cấu gỗ, hài hòa với thiên nhiên.',
                '- Mỗi phong cách có ngôn ngữ hình thức riêng, phản ánh thời đại và văn hóa.',
            ],
            406 => [
                '- Điêu khắc tròn là tượng độc lập ba chiều, có thể xem từ mọi phía.',
                '- Phù điêu là hình nổi trên mặt phẳng nền, gồm nổi cao và nổi thấp.',
                '- Chất liệu điêu khắc phổ biến: đá, gỗ, đồng, thạch cao, đất nung.',
                '- Tượng đài thường đặt nơi công cộng để tưởng niệm nhân vật, sự kiện lịch sử.',
                '- Chọn chất liệu phù hợp quyết định độ bền và vẻ đẹp của tác phẩm điêu khắc.',
            ],
            407 => [
                '- Mỗi đội bóng đá có 11 cầu thủ trên sân: 1 thủ môn và 10 cầu thủ khác.',
                '- Trận đấu chuẩn gồm 2 hiệp, mỗi hiệp 45 phút, nghỉ giữa hiệp tối đa 15 phút.',
                '- Kích thước sân bóng đá 11 người tuân theo quy định của luật FIFA.',
                '- Mỗi đội được thay người theo quy định riêng của từng giải đấu.',
                '- Nắm chắc các con số cơ bản là nền tảng để hiểu luật bóng đá.',
            ],
            408 => [
                '- Luật việt vị xét tại thời điểm đồng đội chuyền bóng, không phải lúc nhận bóng.',
                '- Không bị thổi việt vị khi nhận bóng từ phát bóng, ném biên và phạt góc.',
                '- Phạt trực tiếp: đá thẳng vào khung thành được tính bàn thắng.',
                '- Phạm lỗi trong vòng cấm địa bị phạt đền (penalty), đá từ chấm 11m.',
                '- Một tình huống việt vị cần cả vị trí việt vị và sự tham gia vào tình huống bóng.',
            ],
            409 => [
                '- Bốn tuyến trên sân: thủ môn, hậu vệ, tiền vệ, tiền đạo.',
                '- Thủ môn là người duy nhất được dùng tay trong vòng cấm địa, nhiệm vụ bảo vệ khung thành.',
                '- Hậu vệ là tuyến phòng ngự, ngăn cản đối phương ghi bàn.',
                '- Tiền vệ là cầu nối giữa phòng ngự và tấn công, điều tiết nhịp độ trận đấu.',
                '- Tiền đạo là tuyến tấn công, nhiệm vụ chính là ghi bàn thắng.',
            ],
            410 => [
                '- Sơ đồ chiến thuật ghi số cầu thủ từng tuyến, không tính thủ môn (ví dụ 4-4-2: 4 hậu vệ, 4 tiền vệ, 2 tiền đạo).',
                '- Sơ đồ 4-3-3 với 3 tiền đạo thiên về tấn công, tạo sức ép lớn ở hai biên.',
                '- Nhiều hậu vệ thì thiên về phòng ngự, nhiều tiền đạo thì thiên về tấn công.',
                '- Pressing là chiến thuật gây sức ép ngay trên phần sân của đối phương.',
                '- Phản công là tổ chức tấn công nhanh ngay khi vừa giành lại được bóng.',
            ],
            411 => [
                '- Sân bóng chuyền tiêu chuẩn dài 18m, rộng 9m.',
                '- Chiều cao lưới bóng chuyền nam là 2,43m, lưới nữ là 2,24m.',
                '- Mỗi đội 6 người trên sân, tính điểm theo thể thức rally (mỗi pha bóng đều có điểm).',
                '- Thắng set khi đạt 25 điểm và hơn đối phương ít nhất 2 điểm.',
                '- Ghi nhớ các con số chuẩn giúp hiểu và chơi bóng chuyền đúng luật.',
            ],
            412 => [
                '- Khi giành quyền phát bóng, đội bóng chuyền phải luân chuyển vị trí theo chiều kim đồng hồ.',
                '- Mỗi đội được chạm bóng tối đa 3 lần; riêng chắn bóng không tính là một lần chạm.',
                '- Luân chuyển vị trí đảm bảo mọi cầu thủ đều trải qua các vị trí trên sân.',
                '- Các lỗi kỹ thuật thường gặp: chạm lưới, bóng ra ngoài, quá 3 lần chạm.',
                '- Phân biệt hành vi hợp lệ và phạm lỗi giúp thi đấu đúng luật, tránh mất điểm.',
            ],
            413 => [
                '- Sân cầu lông dài 13,4m; sân đơn rộng 5,18m, sân đôi rộng 6,1m (đơn và đôi chỉ khác chiều rộng).',
                '- Tính điểm rally: mỗi set đánh đến 21 điểm, thắng 2 trong 3 set thì thắng trận.',
                '- Giao cầu phải đánh sang ô chéo sân của đối phương mới hợp lệ.',
                '- Cầu chạm vạch vẫn tính là trong sân.',
                '- Nắm chắc kích thước sân và luật tính điểm để thi đấu đúng luật.',
            ],
            414 => [
                '- Chạm lưới khi cầu còn trong cuộc là lỗi, bị mất điểm ngay.',
                '- Đánh cầu ra ngoài sân hoặc cầu không qua lưới đều bị mất điểm.',
                '- Giao cầu sai kỹ thuật (không chéo sân, đánh quá cao) bị phạt mất điểm.',
                '- Khi có sự cố khách quan không xác định được, trọng tài cho đánh lại pha bóng.',
                '- Hai bên đổi sân theo quy định giữa các set đấu.',
            ],
            415 => [
                '- Sáu nhóm chất dinh dưỡng: bột đường, đạm, béo, vitamin, khoáng chất và nước.',
                '- Bột đường là nhiên liệu chính, cung cấp năng lượng nhanh nhất cho cơ bắp hoạt động.',
                '- Đạm là vật liệu xây dựng và sửa chữa các sợi cơ sau buổi tập.',
                '- Vitamin và khoáng chất giúp chuyển hóa năng lượng, tăng sức đề kháng.',
                '- Nước chiếm phần lớn cơ thể; mất nước làm giảm hiệu suất vận động rõ rệt.',
            ],
            416 => [
                '- Trước buổi tập 2–3 giờ: ăn bữa giàu bột đường, ít béo, dễ tiêu để tránh đầy bụng.',
                '- Trong buổi tập kéo dài: bù nước đều đặn từng ngụm nhỏ, tránh để mất nước giảm hiệu suất.',
                '- Sau buổi tập: bổ sung đạm và bột đường trong 1–2 giờ để phục hồi cơ bắp.',
                '- Tránh đồ ăn nhiều dầu mỡ và nước có gas quanh thời gian tập luyện.',
                '- Dinh dưỡng quanh buổi tập quyết định hiệu quả tập luyện và tốc độ phục hồi.',
            ],
            417 => [
                '- Nguyên tắc tăng tiến dần: tăng khối lượng và cường độ từ từ để cơ thể thích nghi an toàn.',
                '- Nguyên tắc đặc thù: muốn giỏi môn nào phải tập bài tập đặc thù cho môn đó.',
                '- Nguyên tắc đa dạng: thay đổi bài tập để cơ thể phát triển toàn diện, tránh nhàm chán.',
                '- Nguyên tắc nghỉ ngơi, hồi phục: cơ bắp phát triển trong lúc nghỉ; tập quá sức gây chấn thương.',
                '- Tập luyện khoa học là tập từ từ, đúng đặc thù, đa dạng bài tập và có nghỉ ngơi hợp lý.',
            ],
            418 => [
                '- Một buổi tập hoàn chỉnh gồm các giai đoạn: khởi động, phần chính và thả lỏng.',
                '- Khởi động 10–15 phút làm nóng cơ, bôi trơn khớp, giảm nguy cơ chấn thương.',
                '- Thả lỏng sau buổi tập giúp đào thải chất cặn, giảm đau cơ ngày hôm sau.',
                '- Chấn thương thường gặp: chuột rút, bong gân, căng cơ — xử trí ban đầu theo nguyên tắc RICE.',
                '- Dừng tập ngay khi thấy đau bất thường, không cố gắng chịu đựng.',
            ],
            419 => [
                '- Ma trận Eisenhower chia công việc theo hai tiêu chí: quan trọng và khẩn cấp.',
                '- Ô 1 (quan trọng và khẩn cấp): làm ngay lập tức, ưu tiên cao nhất.',
                '- Ô 2 (quan trọng nhưng không khẩn cấp): lên lịch thực hiện — nên đầu tư nhiều cho ô này.',
                '- Ô 3 (khẩn cấp nhưng không quan trọng): ủy thác cho người khác nếu có thể.',
                '- Ô 4 (không quan trọng, không khẩn cấp): hạn chế hoặc loại bỏ khỏi kế hoạch.',
            ],
            420 => [
                '- Kỹ thuật Pomodoro: 25 phút tập trung cao độ rồi nghỉ 5 phút; sau 4 phiên thì nghỉ dài.',
                '- Chu kỳ 25/5 là cốt lõi giúp duy trì sự tập trung mà không kiệt sức.',
                '- Tắt thông báo điện thoại, dọn bàn học gọn gàng để tránh xao nhãng.',
                '- Nguyên nhân trì hoãn thường gặp: việc quá lớn, sợ thất bại, thiếu động lực.',
                '- Chia việc lớn thành việc nhỏ và bắt đầu ngay 5 phút đầu để vượt qua trì hoãn.',
            ],
            421 => [
                '- Ghi chú Cornell chia trang giấy thành 3 phần: ghi chú chính, cột từ khóa/câu hỏi và phần tóm tắt.',
                '- Cột từ khóa/câu hỏi dùng để tự đặt câu hỏi ôn tập sau buổi học.',
                '- Phần tóm tắt ghi ý chính của bài bằng lời của mình sau mỗi buổi học.',
                '- Kỹ thuật Feynman: giải thích lại bài bằng lời đơn giản như đang dạy người khác — chỗ nào vướng là chỗ chưa hiểu.',
                '- Học chủ động (tự kiểm tra, giải thích lại) giúp ghi nhớ lâu hơn nhiều so với đọc thụ động.',
            ],
            422 => [
                '- Ôn tập ngắt quãng (spaced repetition): ôn lại sau 1 ngày, 3 ngày, 1 tuần, 1 tháng giúp nhớ lâu.',
                '- Kỹ thuật tự kiểm tra (retrieval practice): tự gợi nhớ kiến thức thay vì chỉ đọc lại.',
                '- Chiến lược làm bài thi: đọc kỹ đề, làm câu dễ trước, phân bổ thời gian hợp lý.',
                '- Dành thời gian cuối giờ kiểm tra lại bài để tránh sai sót đáng tiếc.',
                '- Ôn cách quãng và tự kiểm tra là hai cách ôn tập hiệu quả nhất.',
            ],
            423 => [
                '- Lý thuyết Holland chia tính cách nghề nghiệp thành 6 nhóm: R – I – A – S – E – C.',
                '- R (Realistic): nhóm kỹ thuật, thích làm việc với máy móc, công cụ.',
                '- I (Investigative): nhóm nghiên cứu, thích tìm tòi, phân tích, khám phá.',
                '- A (Artistic): nhóm nghệ thuật, thích sáng tạo và tự do thể hiện.',
                '- S (Social): nhóm xã hội, thích giúp đỡ và giao tiếp với con người.',
                '- E (Enterprising): nhóm quản lý, thích lãnh đạo và thuyết phục; C (Conventional): nhóm nghiệp vụ, thích trật tự và số liệu.',
            ],
            424 => [
                '- Lĩnh vực công nghệ thông tin: lập trình viên, chuyên gia dữ liệu, an ninh mạng — phát triển nhanh nhất hiện nay.',
                '- Lĩnh vực y tế: bác sĩ, điều dưỡng — chăm sóc sức khỏe cộng đồng.',
                '- Lĩnh vực giáo dục: giáo viên, giảng viên — đào tạo nguồn nhân lực cho xã hội.',
                '- Lĩnh vực kinh tế: kế toán, marketing, quản trị kinh doanh.',
                '- Chuyển đổi số đang tạo ra nhiều nghề mới và thay đổi các nghề truyền thống.',
            ],
            425 => [
                '- Sở thích là điều bạn thích làm — điểm khởi đầu của hướng nghiệp.',
                '- Năng lực là điều bạn làm giỏi — quyết định khả năng thành công với nghề.',
                '- Tính cách là cách bạn hành xử, phản ứng — ảnh hưởng đến sự phù hợp với môi trường làm việc.',
                '- Thích một nghề chưa đủ: thích vẽ chưa chắc vẽ giỏi, cần cả năng lực và tính cách phù hợp.',
                '- Tự đánh giá khách quan cả ba yếu tố giúp chọn nghề đúng đắn.',
            ],
            426 => [
                '- Giá trị nghề nghiệp là điều bạn coi trọng trong công việc: thu nhập, ổn định, sáng tạo, giúp đỡ người khác.',
                '- Xác định giá trị của bản thân giúp chọn nghề phù hợp với mong muốn sâu xa.',
                '- Mục tiêu SMART: Specific (cụ thể), Measurable (đo được), Achievable (khả thi), Relevant (phù hợp), Time-bound (có thời hạn).',
                '- Mục tiêu càng cụ thể càng dễ lập kế hoạch và kiên trì thực hiện.',
                '- Viết mục tiêu ra giấy và xem lại thường xuyên để không lạc hướng.',
            ],
            427 => [
                '- Chọn ngành dựa trên 3 chân kiềng: hiểu mình, hiểu nghề và hiểu điều kiện (học lực, tài chính gia đình).',
                '- Hiểu mình gồm sở thích, năng lực, tính cách và giá trị nghề nghiệp.',
                '- Hiểu nghề gồm công việc thực tế, yêu cầu, cơ hội việc làm và thu nhập.',
                '- Sai lầm cần tránh: chọn ngành theo phong trào, theo bạn bè hoặc chỉ vì ngành đang hot.',
                '- Chọn ngành là quyết định quan trọng — cần thời gian tìm hiểu kỹ và trao đổi với người có kinh nghiệm.',
            ],
            428 => [
                '- Nguồn thông tin đáng tin nhất về trường đại học là website chính thức của trường.',
                '- Các phương thức xét tuyển phổ biến: điểm thi tốt nghiệp THPT, xét học bạ, đánh giá năng lực, xét tuyển thẳng.',
                '- Hai nhóm phương thức chính: dựa trên điểm số và dựa trên thành tích.',
                '- Tìm hiểu kỹ ngành học, học phí và cơ sở vật chất trước khi đăng ký.',
                '- Chuẩn bị hồ sơ đầy đủ và nộp đúng thời hạn quy định.',
            ],
            429 => [
                '- Một CV tốt gồm các phần: thông tin cá nhân, mục tiêu, học vấn, kinh nghiệm/hoạt động và kỹ năng.',
                '- Nguyên tắc quan trọng nhất khi viết CV: trung thực tuyệt đối, không bịa đặt thông tin.',
                '- CV cần gọn gàng, rõ ràng, nhấn mạnh điểm mạnh phù hợp với vị trí ứng tuyển.',
                '- Kiểm tra kỹ chính tả và định dạng trước khi gửi hồ sơ.',
                '- Chuẩn bị hồ sơ đầy đủ theo yêu cầu: CV, đơn ứng tuyển, bằng cấp và giấy tờ liên quan.',
            ],
            430 => [
                '- Trước buổi phỏng vấn: tìm hiểu kỹ về nơi mình ứng tuyển, chuẩn bị câu trả lời cho câu hỏi thường gặp.',
                '- Đến đúng giờ, trang phục lịch sự gọn gàng tạo ấn tượng tốt đầu tiên.',
                '- Trả lời rõ ràng, tự tin và trung thực; nhìn vào mắt người phỏng vấn.',
                '- Chuẩn bị câu hỏi để hỏi lại nhà tuyển dụng thể hiện sự quan tâm nghiêm túc.',
                '- Sau phỏng vấn: cảm ơn lịch sự và chờ đợi, không giục giã.',
            ],
        ];

        foreach (array_chunk($summaries, 25, true) as $chunk) {
            foreach ($chunk as $lessonId => $lines) {
                DB::table('lessons')
                    ->where('id', $lessonId)
                    ->where(function ($query) {
                        $query->whereNull('summary')->orWhere('summary', '');
                    })
                    ->update(['summary' => implode("\n", $lines)]);
            }
        }
    }
}
